// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package testutil

import (
	"context"
	"github.com/proboscis/orch/internal/model"
	"github.com/proboscis/orch/internal/orchapi"
	"sync"
)

// Ensure, that OrchAPIMock does implement orchapi.OrchAPI.
// If this is not the case, regenerate this file with moq.
var _ orchapi.OrchAPI = &OrchAPIMock{}

// OrchAPIMock is a mock implementation of orchapi.OrchAPI.
//
//	func TestSomethingThatUsesOrchAPI(t *testing.T) {
//
//		// make and configure a mocked orchapi.OrchAPI
//		mockedOrchAPI := &OrchAPIMock{
//			AppendEventFunc: func(ctx context.Context, ref orchapi.RunRef, event *orchapi.Event) (*orchapi.AppendEventResult, error) {
//				panic("mock out the AppendEvent method")
//			},
//			CaptureSessionFunc: func(ctx context.Context, ref orchapi.RunRef, lines int) (*orchapi.CaptureResult, error) {
//				panic("mock out the CaptureSession method")
//			},
//			CleanRunWorktreeFunc: func(ctx context.Context, ref orchapi.RunRef) (*orchapi.CleanRunWorktreeResult, error) {
//				panic("mock out the CleanRunWorktree method")
//			},
//			CloseIssueFunc: func(ctx context.Context, issueID model.IssueID) error {
//				panic("mock out the CloseIssue method")
//			},
//			ContinueRunFunc: func(ctx context.Context, req *orchapi.ContinueRunRequest) (*orchapi.ContinueRunResult, error) {
//				panic("mock out the ContinueRun method")
//			},
//			CreateIssueFunc: func(ctx context.Context, req *orchapi.CreateIssueRequest) (*orchapi.Issue, error) {
//				panic("mock out the CreateIssue method")
//			},
//			CreateRunFunc: func(ctx context.Context, req *orchapi.CreateRunRequest) (*orchapi.CreateRunResult, error) {
//				panic("mock out the CreateRun method")
//			},
//			DeleteRunFunc: func(ctx context.Context, ref orchapi.RunRef, opts *orchapi.DeleteRunOptions) (*orchapi.DeleteRunResult, error) {
//				panic("mock out the DeleteRun method")
//			},
//			EnsureOpenCodeServerFunc: func(ctx context.Context) (*orchapi.OpenCodeServerInfo, error) {
//				panic("mock out the EnsureOpenCodeServer method")
//			},
//			GetAttachInfoFunc: func(ctx context.Context, ref orchapi.RunRef) (*orchapi.AttachInfo, error) {
//				panic("mock out the GetAttachInfo method")
//			},
//			GetBranchStateFunc: func(ctx context.Context, ref orchapi.RunRef) (orchapi.BranchState, error) {
//				panic("mock out the GetBranchState method")
//			},
//			GetConfigFunc: func(ctx context.Context) (*orchapi.Config, error) {
//				panic("mock out the GetConfig method")
//			},
//			GetDaemonLogFunc: func(ctx context.Context, lines int) (string, error) {
//				panic("mock out the GetDaemonLog method")
//			},
//			GetDaemonStatusFunc: func(ctx context.Context) (*orchapi.DaemonStatus, error) {
//				panic("mock out the GetDaemonStatus method")
//			},
//			GetDiffFunc: func(ctx context.Context, ref orchapi.RunRef) (string, error) {
//				panic("mock out the GetDiff method")
//			},
//			GetDiffStatsFunc: func(ctx context.Context, ref orchapi.RunRef) (*orchapi.DiffStats, error) {
//				panic("mock out the GetDiffStats method")
//			},
//			GetIssueFunc: func(ctx context.Context, issueID model.IssueID) (*orchapi.Issue, error) {
//				panic("mock out the GetIssue method")
//			},
//			GetLatestRunFunc: func(ctx context.Context, issueID model.IssueID) (*orchapi.Run, error) {
//				panic("mock out the GetLatestRun method")
//			},
//			GetRunFunc: func(ctx context.Context, issueID model.IssueID, runID model.RunID) (*orchapi.Run, error) {
//				panic("mock out the GetRun method")
//			},
//			InjectInitialPromptFunc: func(ctx context.Context, ref orchapi.RunRef, prompt string) error {
//				panic("mock out the InjectInitialPrompt method")
//			},
//			ListIssuesFunc: func(ctx context.Context, filter *orchapi.ListIssuesFilter) (*orchapi.ListIssuesResult, error) {
//				panic("mock out the ListIssues method")
//			},
//			ListRunsFunc: func(ctx context.Context, filter *orchapi.ListRunsFilter) (*orchapi.ListRunsResult, error) {
//				panic("mock out the ListRuns method")
//			},
//			MarkRunResolvedFunc: func(ctx context.Context, ref orchapi.RunRef) error {
//				panic("mock out the MarkRunResolved method")
//			},
//			PingFunc: func(ctx context.Context) error {
//				panic("mock out the Ping method")
//			},
//			QueryOpenCodeServerFunc: func(ctx context.Context, port int) (*orchapi.QueryOpenCodeServerResult, error) {
//				panic("mock out the QueryOpenCodeServer method")
//			},
//			ReadAgentPromptFunc: func(ctx context.Context, ref orchapi.RunRef) (string, error) {
//				panic("mock out the ReadAgentPrompt method")
//			},
//			ReadFileFunc: func(ctx context.Context, path string) ([]byte, error) {
//				panic("mock out the ReadFile method")
//			},
//			RepairStateFunc: func(ctx context.Context, opts *orchapi.RepairOptions) (*orchapi.RepairResult, error) {
//				panic("mock out the RepairState method")
//			},
//			ResolveIssueFunc: func(ctx context.Context, issueID model.IssueID, force bool) error {
//				panic("mock out the ResolveIssue method")
//			},
//			ResolveRunFunc: func(ctx context.Context, ref orchapi.RunRef) (*orchapi.Run, error) {
//				panic("mock out the ResolveRun method")
//			},
//			SendMessageFunc: func(ctx context.Context, ref orchapi.RunRef, message string, noEnter bool) error {
//				panic("mock out the SendMessage method")
//			},
//			SetIssueStatusFunc: func(ctx context.Context, issueID model.IssueID, status orchapi.IssueStatus) error {
//				panic("mock out the SetIssueStatus method")
//			},
//			StartRunFunc: func(ctx context.Context, req *orchapi.StartRunRequest) (*orchapi.StartRunResult, error) {
//				panic("mock out the StartRun method")
//			},
//			StopRunFunc: func(ctx context.Context, ref orchapi.RunRef, force bool) (*orchapi.StopRunResult, error) {
//				panic("mock out the StopRun method")
//			},
//			StreamRunEventsFunc: func(ctx context.Context, filter *orchapi.RunEventFilter) (orchapi.RunEventStream, error) {
//				panic("mock out the StreamRunEvents method")
//			},
//			UpdateIssueFunc: func(ctx context.Context, issueID model.IssueID, req *orchapi.UpdateIssueRequest) (*orchapi.Issue, error) {
//				panic("mock out the UpdateIssue method")
//			},
//			ValidateIssueFilesFunc: func(ctx context.Context, issueID model.IssueID) (*orchapi.ValidateIssueFilesResult, error) {
//				panic("mock out the ValidateIssueFiles method")
//			},
//			WaitForRunsFunc: func(ctx context.Context, refs []string, timeoutSeconds int) (*orchapi.WaitForRunsResult, error) {
//				panic("mock out the WaitForRuns method")
//			},
//			WriteAgentPromptFunc: func(ctx context.Context, ref orchapi.RunRef, content string) error {
//				panic("mock out the WriteAgentPrompt method")
//			},
//			WriteFileFunc: func(ctx context.Context, path string, content []byte, perm uint32) error {
//				panic("mock out the WriteFile method")
//			},
//		}
//
//		// use mockedOrchAPI in code that requires orchapi.OrchAPI
//		// and then make assertions.
//
//	}
type OrchAPIMock struct {
	// AppendEventFunc mocks the AppendEvent method.
	AppendEventFunc func(ctx context.Context, ref orchapi.RunRef, event *orchapi.Event) (*orchapi.AppendEventResult, error)

	// CaptureSessionFunc mocks the CaptureSession method.
	CaptureSessionFunc func(ctx context.Context, ref orchapi.RunRef, lines int) (*orchapi.CaptureResult, error)

	// CleanRunWorktreeFunc mocks the CleanRunWorktree method.
	CleanRunWorktreeFunc func(ctx context.Context, ref orchapi.RunRef) (*orchapi.CleanRunWorktreeResult, error)

	// CloseIssueFunc mocks the CloseIssue method.
	CloseIssueFunc func(ctx context.Context, issueID model.IssueID) error

	// ContinueRunFunc mocks the ContinueRun method.
	ContinueRunFunc func(ctx context.Context, req *orchapi.ContinueRunRequest) (*orchapi.ContinueRunResult, error)

	// CreateIssueFunc mocks the CreateIssue method.
	CreateIssueFunc func(ctx context.Context, req *orchapi.CreateIssueRequest) (*orchapi.Issue, error)

	// CreateRunFunc mocks the CreateRun method.
	CreateRunFunc func(ctx context.Context, req *orchapi.CreateRunRequest) (*orchapi.CreateRunResult, error)

	// DeleteRunFunc mocks the DeleteRun method.
	DeleteRunFunc func(ctx context.Context, ref orchapi.RunRef, opts *orchapi.DeleteRunOptions) (*orchapi.DeleteRunResult, error)

	// EnsureOpenCodeServerFunc mocks the EnsureOpenCodeServer method.
	EnsureOpenCodeServerFunc func(ctx context.Context) (*orchapi.OpenCodeServerInfo, error)

	// GetAttachInfoFunc mocks the GetAttachInfo method.
	GetAttachInfoFunc func(ctx context.Context, ref orchapi.RunRef) (*orchapi.AttachInfo, error)

	// GetBranchStateFunc mocks the GetBranchState method.
	GetBranchStateFunc func(ctx context.Context, ref orchapi.RunRef) (orchapi.BranchState, error)

	// GetConfigFunc mocks the GetConfig method.
	GetConfigFunc func(ctx context.Context) (*orchapi.Config, error)

	// GetDaemonLogFunc mocks the GetDaemonLog method.
	GetDaemonLogFunc func(ctx context.Context, lines int) (string, error)

	// GetDaemonStatusFunc mocks the GetDaemonStatus method.
	GetDaemonStatusFunc func(ctx context.Context) (*orchapi.DaemonStatus, error)

	// GetDiffFunc mocks the GetDiff method.
	GetDiffFunc func(ctx context.Context, ref orchapi.RunRef) (string, error)

	// GetDiffStatsFunc mocks the GetDiffStats method.
	GetDiffStatsFunc func(ctx context.Context, ref orchapi.RunRef) (*orchapi.DiffStats, error)

	// GetIssueFunc mocks the GetIssue method.
	GetIssueFunc func(ctx context.Context, issueID model.IssueID) (*orchapi.Issue, error)

	// GetLatestRunFunc mocks the GetLatestRun method.
	GetLatestRunFunc func(ctx context.Context, issueID model.IssueID) (*orchapi.Run, error)

	// GetRunFunc mocks the GetRun method.
	GetRunFunc func(ctx context.Context, issueID model.IssueID, runID model.RunID) (*orchapi.Run, error)

	// InjectInitialPromptFunc mocks the InjectInitialPrompt method.
	InjectInitialPromptFunc func(ctx context.Context, ref orchapi.RunRef, prompt string) error

	// ListIssuesFunc mocks the ListIssues method.
	ListIssuesFunc func(ctx context.Context, filter *orchapi.ListIssuesFilter) (*orchapi.ListIssuesResult, error)

	// ListRunsFunc mocks the ListRuns method.
	ListRunsFunc func(ctx context.Context, filter *orchapi.ListRunsFilter) (*orchapi.ListRunsResult, error)

	// MarkRunResolvedFunc mocks the MarkRunResolved method.
	MarkRunResolvedFunc func(ctx context.Context, ref orchapi.RunRef) error

	// PingFunc mocks the Ping method.
	PingFunc func(ctx context.Context) error

	// QueryOpenCodeServerFunc mocks the QueryOpenCodeServer method.
	QueryOpenCodeServerFunc func(ctx context.Context, port int) (*orchapi.QueryOpenCodeServerResult, error)

	// ReadAgentPromptFunc mocks the ReadAgentPrompt method.
	ReadAgentPromptFunc func(ctx context.Context, ref orchapi.RunRef) (string, error)

	// ReadFileFunc mocks the ReadFile method.
	ReadFileFunc func(ctx context.Context, path string) ([]byte, error)

	// RepairStateFunc mocks the RepairState method.
	RepairStateFunc func(ctx context.Context, opts *orchapi.RepairOptions) (*orchapi.RepairResult, error)

	// ResolveIssueFunc mocks the ResolveIssue method.
	ResolveIssueFunc func(ctx context.Context, issueID model.IssueID, force bool) error

	// ResolveRunFunc mocks the ResolveRun method.
	ResolveRunFunc func(ctx context.Context, ref orchapi.RunRef) (*orchapi.Run, error)

	// SendMessageFunc mocks the SendMessage method.
	SendMessageFunc func(ctx context.Context, ref orchapi.RunRef, message string, noEnter bool) error

	// SetIssueStatusFunc mocks the SetIssueStatus method.
	SetIssueStatusFunc func(ctx context.Context, issueID model.IssueID, status orchapi.IssueStatus) error

	// StartRunFunc mocks the StartRun method.
	StartRunFunc func(ctx context.Context, req *orchapi.StartRunRequest) (*orchapi.StartRunResult, error)

	// StopRunFunc mocks the StopRun method.
	StopRunFunc func(ctx context.Context, ref orchapi.RunRef, force bool) (*orchapi.StopRunResult, error)

	// StreamRunEventsFunc mocks the StreamRunEvents method.
	StreamRunEventsFunc func(ctx context.Context, filter *orchapi.RunEventFilter) (orchapi.RunEventStream, error)

	// UpdateIssueFunc mocks the UpdateIssue method.
	UpdateIssueFunc func(ctx context.Context, issueID model.IssueID, req *orchapi.UpdateIssueRequest) (*orchapi.Issue, error)

	// ValidateIssueFilesFunc mocks the ValidateIssueFiles method.
	ValidateIssueFilesFunc func(ctx context.Context, issueID model.IssueID) (*orchapi.ValidateIssueFilesResult, error)

	// WaitForRunsFunc mocks the WaitForRuns method.
	WaitForRunsFunc func(ctx context.Context, refs []string, timeoutSeconds int) (*orchapi.WaitForRunsResult, error)

	// WriteAgentPromptFunc mocks the WriteAgentPrompt method.
	WriteAgentPromptFunc func(ctx context.Context, ref orchapi.RunRef, content string) error

	// WriteFileFunc mocks the WriteFile method.
	WriteFileFunc func(ctx context.Context, path string, content []byte, perm uint32) error

	// calls tracks calls to the methods.
	calls struct {
		// AppendEvent holds details about calls to the AppendEvent method.
		AppendEvent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref orchapi.RunRef
			// Event is the event argument value.
			Event *orchapi.Event
		}
		// CaptureSession holds details about calls to the CaptureSession method.
		CaptureSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref orchapi.RunRef
			// Lines is the lines argument value.
			Lines int
		}
		// CleanRunWorktree holds details about calls to the CleanRunWorktree method.
		CleanRunWorktree []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref orchapi.RunRef
		}
		// CloseIssue holds details about calls to the CloseIssue method.
		CloseIssue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// IssueID is the issueID argument value.
			IssueID model.IssueID
		}
		// ContinueRun holds details about calls to the ContinueRun method.
		ContinueRun []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *orchapi.ContinueRunRequest
		}
		// CreateIssue holds details about calls to the CreateIssue method.
		CreateIssue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *orchapi.CreateIssueRequest
		}
		// CreateRun holds details about calls to the CreateRun method.
		CreateRun []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *orchapi.CreateRunRequest
		}
		// DeleteRun holds details about calls to the DeleteRun method.
		DeleteRun []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref orchapi.RunRef
			// Opts is the opts argument value.
			Opts *orchapi.DeleteRunOptions
		}
		// EnsureOpenCodeServer holds details about calls to the EnsureOpenCodeServer method.
		EnsureOpenCodeServer []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetAttachInfo holds details about calls to the GetAttachInfo method.
		GetAttachInfo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref orchapi.RunRef
		}
		// GetBranchState holds details about calls to the GetBranchState method.
		GetBranchState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref orchapi.RunRef
		}
		// GetConfig holds details about calls to the GetConfig method.
		GetConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetDaemonLog holds details about calls to the GetDaemonLog method.
		GetDaemonLog []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Lines is the lines argument value.
			Lines int
		}
		// GetDaemonStatus holds details about calls to the GetDaemonStatus method.
		GetDaemonStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetDiff holds details about calls to the GetDiff method.
		GetDiff []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref orchapi.RunRef
		}
		// GetDiffStats holds details about calls to the GetDiffStats method.
		GetDiffStats []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref orchapi.RunRef
		}
		// GetIssue holds details about calls to the GetIssue method.
		GetIssue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// IssueID is the issueID argument value.
			IssueID model.IssueID
		}
		// GetLatestRun holds details about calls to the GetLatestRun method.
		GetLatestRun []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// IssueID is the issueID argument value.
			IssueID model.IssueID
		}
		// GetRun holds details about calls to the GetRun method.
		GetRun []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// IssueID is the issueID argument value.
			IssueID model.IssueID
			// RunID is the runID argument value.
			RunID model.RunID
		}
		// InjectInitialPrompt holds details about calls to the InjectInitialPrompt method.
		InjectInitialPrompt []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref orchapi.RunRef
			// Prompt is the prompt argument value.
			Prompt string
		}
		// ListIssues holds details about calls to the ListIssues method.
		ListIssues []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filter is the filter argument value.
			Filter *orchapi.ListIssuesFilter
		}
		// ListRuns holds details about calls to the ListRuns method.
		ListRuns []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filter is the filter argument value.
			Filter *orchapi.ListRunsFilter
		}
		// MarkRunResolved holds details about calls to the MarkRunResolved method.
		MarkRunResolved []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref orchapi.RunRef
		}
		// Ping holds details about calls to the Ping method.
		Ping []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// QueryOpenCodeServer holds details about calls to the QueryOpenCodeServer method.
		QueryOpenCodeServer []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Port is the port argument value.
			Port int
		}
		// ReadAgentPrompt holds details about calls to the ReadAgentPrompt method.
		ReadAgentPrompt []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref orchapi.RunRef
		}
		// ReadFile holds details about calls to the ReadFile method.
		ReadFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
		}
		// RepairState holds details about calls to the RepairState method.
		RepairState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts *orchapi.RepairOptions
		}
		// ResolveIssue holds details about calls to the ResolveIssue method.
		ResolveIssue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// IssueID is the issueID argument value.
			IssueID model.IssueID
			// Force is the force argument value.
			Force bool
		}
		// ResolveRun holds details about calls to the ResolveRun method.
		ResolveRun []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref orchapi.RunRef
		}
		// SendMessage holds details about calls to the SendMessage method.
		SendMessage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref orchapi.RunRef
			// Message is the message argument value.
			Message string
			// NoEnter is the noEnter argument value.
			NoEnter bool
		}
		// SetIssueStatus holds details about calls to the SetIssueStatus method.
		SetIssueStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// IssueID is the issueID argument value.
			IssueID model.IssueID
			// Status is the status argument value.
			Status orchapi.IssueStatus
		}
		// StartRun holds details about calls to the StartRun method.
		StartRun []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *orchapi.StartRunRequest
		}
		// StopRun holds details about calls to the StopRun method.
		StopRun []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref orchapi.RunRef
			// Force is the force argument value.
			Force bool
		}
		// StreamRunEvents holds details about calls to the StreamRunEvents method.
		StreamRunEvents []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filter is the filter argument value.
			Filter *orchapi.RunEventFilter
		}
		// UpdateIssue holds details about calls to the UpdateIssue method.
		UpdateIssue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// IssueID is the issueID argument value.
			IssueID model.IssueID
			// Req is the req argument value.
			Req *orchapi.UpdateIssueRequest
		}
		// ValidateIssueFiles holds details about calls to the ValidateIssueFiles method.
		ValidateIssueFiles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// IssueID is the issueID argument value.
			IssueID model.IssueID
		}
		// WaitForRuns holds details about calls to the WaitForRuns method.
		WaitForRuns []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Refs is the refs argument value.
			Refs []string
			// TimeoutSeconds is the timeoutSeconds argument value.
			TimeoutSeconds int
		}
		// WriteAgentPrompt holds details about calls to the WriteAgentPrompt method.
		WriteAgentPrompt []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref orchapi.RunRef
			// Content is the content argument value.
			Content string
		}
		// WriteFile holds details about calls to the WriteFile method.
		WriteFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
			// Content is the content argument value.
			Content []byte
			// Perm is the perm argument value.
			Perm uint32
		}
	}
	lockAppendEvent          sync.RWMutex
	lockCaptureSession       sync.RWMutex
	lockCleanRunWorktree     sync.RWMutex
	lockCloseIssue           sync.RWMutex
	lockContinueRun          sync.RWMutex
	lockCreateIssue          sync.RWMutex
	lockCreateRun            sync.RWMutex
	lockDeleteRun            sync.RWMutex
	lockEnsureOpenCodeServer sync.RWMutex
	lockGetAttachInfo        sync.RWMutex
	lockGetBranchState       sync.RWMutex
	lockGetConfig            sync.RWMutex
	lockGetDaemonLog         sync.RWMutex
	lockGetDaemonStatus      sync.RWMutex
	lockGetDiff              sync.RWMutex
	lockGetDiffStats         sync.RWMutex
	lockGetIssue             sync.RWMutex
	lockGetLatestRun         sync.RWMutex
	lockGetRun               sync.RWMutex
	lockInjectInitialPrompt  sync.RWMutex
	lockListIssues           sync.RWMutex
	lockListRuns             sync.RWMutex
	lockMarkRunResolved      sync.RWMutex
	lockPing                 sync.RWMutex
	lockQueryOpenCodeServer  sync.RWMutex
	lockReadAgentPrompt      sync.RWMutex
	lockReadFile             sync.RWMutex
	lockRepairState          sync.RWMutex
	lockResolveIssue         sync.RWMutex
	lockResolveRun           sync.RWMutex
	lockSendMessage          sync.RWMutex
	lockSetIssueStatus       sync.RWMutex
	lockStartRun             sync.RWMutex
	lockStopRun              sync.RWMutex
	lockStreamRunEvents      sync.RWMutex
	lockUpdateIssue          sync.RWMutex
	lockValidateIssueFiles   sync.RWMutex
	lockWaitForRuns          sync.RWMutex
	lockWriteAgentPrompt     sync.RWMutex
	lockWriteFile            sync.RWMutex
}

// AppendEvent calls AppendEventFunc.
func (mock *OrchAPIMock) AppendEvent(ctx context.Context, ref orchapi.RunRef, event *orchapi.Event) (*orchapi.AppendEventResult, error) {
	if mock.AppendEventFunc == nil {
		panic("OrchAPIMock.AppendEventFunc: method is nil but OrchAPI.AppendEvent was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Ref   orchapi.RunRef
		Event *orchapi.Event
	}{
		Ctx:   ctx,
		Ref:   ref,
		Event: event,
	}
	mock.lockAppendEvent.Lock()
	mock.calls.AppendEvent = append(mock.calls.AppendEvent, callInfo)
	mock.lockAppendEvent.Unlock()
	return mock.AppendEventFunc(ctx, ref, event)
}

// AppendEventCalls gets all the calls that were made to AppendEvent.
// Check the length with:
//
//	len(mockedOrchAPI.AppendEventCalls())
func (mock *OrchAPIMock) AppendEventCalls() []struct {
	Ctx   context.Context
	Ref   orchapi.RunRef
	Event *orchapi.Event
} {
	var calls []struct {
		Ctx   context.Context
		Ref   orchapi.RunRef
		Event *orchapi.Event
	}
	mock.lockAppendEvent.RLock()
	calls = mock.calls.AppendEvent
	mock.lockAppendEvent.RUnlock()
	return calls
}

// CaptureSession calls CaptureSessionFunc.
func (mock *OrchAPIMock) CaptureSession(ctx context.Context, ref orchapi.RunRef, lines int) (*orchapi.CaptureResult, error) {
	if mock.CaptureSessionFunc == nil {
		panic("OrchAPIMock.CaptureSessionFunc: method is nil but OrchAPI.CaptureSession was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Ref   orchapi.RunRef
		Lines int
	}{
		Ctx:   ctx,
		Ref:   ref,
		Lines: lines,
	}
	mock.lockCaptureSession.Lock()
	mock.calls.CaptureSession = append(mock.calls.CaptureSession, callInfo)
	mock.lockCaptureSession.Unlock()
	return mock.CaptureSessionFunc(ctx, ref, lines)
}

// CaptureSessionCalls gets all the calls that were made to CaptureSession.
// Check the length with:
//
//	len(mockedOrchAPI.CaptureSessionCalls())
func (mock *OrchAPIMock) CaptureSessionCalls() []struct {
	Ctx   context.Context
	Ref   orchapi.RunRef
	Lines int
} {
	var calls []struct {
		Ctx   context.Context
		Ref   orchapi.RunRef
		Lines int
	}
	mock.lockCaptureSession.RLock()
	calls = mock.calls.CaptureSession
	mock.lockCaptureSession.RUnlock()
	return calls
}

// CleanRunWorktree calls CleanRunWorktreeFunc.
func (mock *OrchAPIMock) CleanRunWorktree(ctx context.Context, ref orchapi.RunRef) (*orchapi.CleanRunWorktreeResult, error) {
	if mock.CleanRunWorktreeFunc == nil {
		panic("OrchAPIMock.CleanRunWorktreeFunc: method is nil but OrchAPI.CleanRunWorktree was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ref orchapi.RunRef
	}{
		Ctx: ctx,
		Ref: ref,
	}
	mock.lockCleanRunWorktree.Lock()
	mock.calls.CleanRunWorktree = append(mock.calls.CleanRunWorktree, callInfo)
	mock.lockCleanRunWorktree.Unlock()
	return mock.CleanRunWorktreeFunc(ctx, ref)
}

// CleanRunWorktreeCalls gets all the calls that were made to CleanRunWorktree.
// Check the length with:
//
//	len(mockedOrchAPI.CleanRunWorktreeCalls())
func (mock *OrchAPIMock) CleanRunWorktreeCalls() []struct {
	Ctx context.Context
	Ref orchapi.RunRef
} {
	var calls []struct {
		Ctx context.Context
		Ref orchapi.RunRef
	}
	mock.lockCleanRunWorktree.RLock()
	calls = mock.calls.CleanRunWorktree
	mock.lockCleanRunWorktree.RUnlock()
	return calls
}

// CloseIssue calls CloseIssueFunc.
func (mock *OrchAPIMock) CloseIssue(ctx context.Context, issueID model.IssueID) error {
	if mock.CloseIssueFunc == nil {
		panic("OrchAPIMock.CloseIssueFunc: method is nil but OrchAPI.CloseIssue was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		IssueID model.IssueID
	}{
		Ctx:     ctx,
		IssueID: issueID,
	}
	mock.lockCloseIssue.Lock()
	mock.calls.CloseIssue = append(mock.calls.CloseIssue, callInfo)
	mock.lockCloseIssue.Unlock()
	return mock.CloseIssueFunc(ctx, issueID)
}

// CloseIssueCalls gets all the calls that were made to CloseIssue.
// Check the length with:
//
//	len(mockedOrchAPI.CloseIssueCalls())
func (mock *OrchAPIMock) CloseIssueCalls() []struct {
	Ctx     context.Context
	IssueID model.IssueID
} {
	var calls []struct {
		Ctx     context.Context
		IssueID model.IssueID
	}
	mock.lockCloseIssue.RLock()
	calls = mock.calls.CloseIssue
	mock.lockCloseIssue.RUnlock()
	return calls
}

// ContinueRun calls ContinueRunFunc.
func (mock *OrchAPIMock) ContinueRun(ctx context.Context, req *orchapi.ContinueRunRequest) (*orchapi.ContinueRunResult, error) {
	if mock.ContinueRunFunc == nil {
		panic("OrchAPIMock.ContinueRunFunc: method is nil but OrchAPI.ContinueRun was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *orchapi.ContinueRunRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockContinueRun.Lock()
	mock.calls.ContinueRun = append(mock.calls.ContinueRun, callInfo)
	mock.lockContinueRun.Unlock()
	return mock.ContinueRunFunc(ctx, req)
}

// ContinueRunCalls gets all the calls that were made to ContinueRun.
// Check the length with:
//
//	len(mockedOrchAPI.ContinueRunCalls())
func (mock *OrchAPIMock) ContinueRunCalls() []struct {
	Ctx context.Context
	Req *orchapi.ContinueRunRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *orchapi.ContinueRunRequest
	}
	mock.lockContinueRun.RLock()
	calls = mock.calls.ContinueRun
	mock.lockContinueRun.RUnlock()
	return calls
}

// CreateIssue calls CreateIssueFunc.
func (mock *OrchAPIMock) CreateIssue(ctx context.Context, req *orchapi.CreateIssueRequest) (*orchapi.Issue, error) {
	if mock.CreateIssueFunc == nil {
		panic("OrchAPIMock.CreateIssueFunc: method is nil but OrchAPI.CreateIssue was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *orchapi.CreateIssueRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockCreateIssue.Lock()
	mock.calls.CreateIssue = append(mock.calls.CreateIssue, callInfo)
	mock.lockCreateIssue.Unlock()
	return mock.CreateIssueFunc(ctx, req)
}

// CreateIssueCalls gets all the calls that were made to CreateIssue.
// Check the length with:
//
//	len(mockedOrchAPI.CreateIssueCalls())
func (mock *OrchAPIMock) CreateIssueCalls() []struct {
	Ctx context.Context
	Req *orchapi.CreateIssueRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *orchapi.CreateIssueRequest
	}
	mock.lockCreateIssue.RLock()
	calls = mock.calls.CreateIssue
	mock.lockCreateIssue.RUnlock()
	return calls
}

// CreateRun calls CreateRunFunc.
func (mock *OrchAPIMock) CreateRun(ctx context.Context, req *orchapi.CreateRunRequest) (*orchapi.CreateRunResult, error) {
	if mock.CreateRunFunc == nil {
		panic("OrchAPIMock.CreateRunFunc: method is nil but OrchAPI.CreateRun was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *orchapi.CreateRunRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockCreateRun.Lock()
	mock.calls.CreateRun = append(mock.calls.CreateRun, callInfo)
	mock.lockCreateRun.Unlock()
	return mock.CreateRunFunc(ctx, req)
}

// CreateRunCalls gets all the calls that were made to CreateRun.
// Check the length with:
//
//	len(mockedOrchAPI.CreateRunCalls())
func (mock *OrchAPIMock) CreateRunCalls() []struct {
	Ctx context.Context
	Req *orchapi.CreateRunRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *orchapi.CreateRunRequest
	}
	mock.lockCreateRun.RLock()
	calls = mock.calls.CreateRun
	mock.lockCreateRun.RUnlock()
	return calls
}

// DeleteRun calls DeleteRunFunc.
func (mock *OrchAPIMock) DeleteRun(ctx context.Context, ref orchapi.RunRef, opts *orchapi.DeleteRunOptions) (*orchapi.DeleteRunResult, error) {
	if mock.DeleteRunFunc == nil {
		panic("OrchAPIMock.DeleteRunFunc: method is nil but OrchAPI.DeleteRun was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Ref  orchapi.RunRef
		Opts *orchapi.DeleteRunOptions
	}{
		Ctx:  ctx,
		Ref:  ref,
		Opts: opts,
	}
	mock.lockDeleteRun.Lock()
	mock.calls.DeleteRun = append(mock.calls.DeleteRun, callInfo)
	mock.lockDeleteRun.Unlock()
	return mock.DeleteRunFunc(ctx, ref, opts)
}

// DeleteRunCalls gets all the calls that were made to DeleteRun.
// Check the length with:
//
//	len(mockedOrchAPI.DeleteRunCalls())
func (mock *OrchAPIMock) DeleteRunCalls() []struct {
	Ctx  context.Context
	Ref  orchapi.RunRef
	Opts *orchapi.DeleteRunOptions
} {
	var calls []struct {
		Ctx  context.Context
		Ref  orchapi.RunRef
		Opts *orchapi.DeleteRunOptions
	}
	mock.lockDeleteRun.RLock()
	calls = mock.calls.DeleteRun
	mock.lockDeleteRun.RUnlock()
	return calls
}

// EnsureOpenCodeServer calls EnsureOpenCodeServerFunc.
func (mock *OrchAPIMock) EnsureOpenCodeServer(ctx context.Context) (*orchapi.OpenCodeServerInfo, error) {
	if mock.EnsureOpenCodeServerFunc == nil {
		panic("OrchAPIMock.EnsureOpenCodeServerFunc: method is nil but OrchAPI.EnsureOpenCodeServer was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockEnsureOpenCodeServer.Lock()
	mock.calls.EnsureOpenCodeServer = append(mock.calls.EnsureOpenCodeServer, callInfo)
	mock.lockEnsureOpenCodeServer.Unlock()
	return mock.EnsureOpenCodeServerFunc(ctx)
}

// EnsureOpenCodeServerCalls gets all the calls that were made to EnsureOpenCodeServer.
// Check the length with:
//
//	len(mockedOrchAPI.EnsureOpenCodeServerCalls())
func (mock *OrchAPIMock) EnsureOpenCodeServerCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockEnsureOpenCodeServer.RLock()
	calls = mock.calls.EnsureOpenCodeServer
	mock.lockEnsureOpenCodeServer.RUnlock()
	return calls
}

// GetAttachInfo calls GetAttachInfoFunc.
func (mock *OrchAPIMock) GetAttachInfo(ctx context.Context, ref orchapi.RunRef) (*orchapi.AttachInfo, error) {
	if mock.GetAttachInfoFunc == nil {
		panic("OrchAPIMock.GetAttachInfoFunc: method is nil but OrchAPI.GetAttachInfo was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ref orchapi.RunRef
	}{
		Ctx: ctx,
		Ref: ref,
	}
	mock.lockGetAttachInfo.Lock()
	mock.calls.GetAttachInfo = append(mock.calls.GetAttachInfo, callInfo)
	mock.lockGetAttachInfo.Unlock()
	return mock.GetAttachInfoFunc(ctx, ref)
}

// GetAttachInfoCalls gets all the calls that were made to GetAttachInfo.
// Check the length with:
//
//	len(mockedOrchAPI.GetAttachInfoCalls())
func (mock *OrchAPIMock) GetAttachInfoCalls() []struct {
	Ctx context.Context
	Ref orchapi.RunRef
} {
	var calls []struct {
		Ctx context.Context
		Ref orchapi.RunRef
	}
	mock.lockGetAttachInfo.RLock()
	calls = mock.calls.GetAttachInfo
	mock.lockGetAttachInfo.RUnlock()
	return calls
}

// GetBranchState calls GetBranchStateFunc.
func (mock *OrchAPIMock) GetBranchState(ctx context.Context, ref orchapi.RunRef) (orchapi.BranchState, error) {
	if mock.GetBranchStateFunc == nil {
		panic("OrchAPIMock.GetBranchStateFunc: method is nil but OrchAPI.GetBranchState was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ref orchapi.RunRef
	}{
		Ctx: ctx,
		Ref: ref,
	}
	mock.lockGetBranchState.Lock()
	mock.calls.GetBranchState = append(mock.calls.GetBranchState, callInfo)
	mock.lockGetBranchState.Unlock()
	return mock.GetBranchStateFunc(ctx, ref)
}

// GetBranchStateCalls gets all the calls that were made to GetBranchState.
// Check the length with:
//
//	len(mockedOrchAPI.GetBranchStateCalls())
func (mock *OrchAPIMock) GetBranchStateCalls() []struct {
	Ctx context.Context
	Ref orchapi.RunRef
} {
	var calls []struct {
		Ctx context.Context
		Ref orchapi.RunRef
	}
	mock.lockGetBranchState.RLock()
	calls = mock.calls.GetBranchState
	mock.lockGetBranchState.RUnlock()
	return calls
}

// GetConfig calls GetConfigFunc.
func (mock *OrchAPIMock) GetConfig(ctx context.Context) (*orchapi.Config, error) {
	if mock.GetConfigFunc == nil {
		panic("OrchAPIMock.GetConfigFunc: method is nil but OrchAPI.GetConfig was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetConfig.Lock()
	mock.calls.GetConfig = append(mock.calls.GetConfig, callInfo)
	mock.lockGetConfig.Unlock()
	return mock.GetConfigFunc(ctx)
}

// GetConfigCalls gets all the calls that were made to GetConfig.
// Check the length with:
//
//	len(mockedOrchAPI.GetConfigCalls())
func (mock *OrchAPIMock) GetConfigCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetConfig.RLock()
	calls = mock.calls.GetConfig
	mock.lockGetConfig.RUnlock()
	return calls
}

// GetDaemonLog calls GetDaemonLogFunc.
func (mock *OrchAPIMock) GetDaemonLog(ctx context.Context, lines int) (string, error) {
	if mock.GetDaemonLogFunc == nil {
		panic("OrchAPIMock.GetDaemonLogFunc: method is nil but OrchAPI.GetDaemonLog was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Lines int
	}{
		Ctx:   ctx,
		Lines: lines,
	}
	mock.lockGetDaemonLog.Lock()
	mock.calls.GetDaemonLog = append(mock.calls.GetDaemonLog, callInfo)
	mock.lockGetDaemonLog.Unlock()
	return mock.GetDaemonLogFunc(ctx, lines)
}

// GetDaemonLogCalls gets all the calls that were made to GetDaemonLog.
// Check the length with:
//
//	len(mockedOrchAPI.GetDaemonLogCalls())
func (mock *OrchAPIMock) GetDaemonLogCalls() []struct {
	Ctx   context.Context
	Lines int
} {
	var calls []struct {
		Ctx   context.Context
		Lines int
	}
	mock.lockGetDaemonLog.RLock()
	calls = mock.calls.GetDaemonLog
	mock.lockGetDaemonLog.RUnlock()
	return calls
}

// GetDaemonStatus calls GetDaemonStatusFunc.
func (mock *OrchAPIMock) GetDaemonStatus(ctx context.Context) (*orchapi.DaemonStatus, error) {
	if mock.GetDaemonStatusFunc == nil {
		panic("OrchAPIMock.GetDaemonStatusFunc: method is nil but OrchAPI.GetDaemonStatus was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetDaemonStatus.Lock()
	mock.calls.GetDaemonStatus = append(mock.calls.GetDaemonStatus, callInfo)
	mock.lockGetDaemonStatus.Unlock()
	return mock.GetDaemonStatusFunc(ctx)
}

// GetDaemonStatusCalls gets all the calls that were made to GetDaemonStatus.
// Check the length with:
//
//	len(mockedOrchAPI.GetDaemonStatusCalls())
func (mock *OrchAPIMock) GetDaemonStatusCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetDaemonStatus.RLock()
	calls = mock.calls.GetDaemonStatus
	mock.lockGetDaemonStatus.RUnlock()
	return calls
}

// GetDiff calls GetDiffFunc.
func (mock *OrchAPIMock) GetDiff(ctx context.Context, ref orchapi.RunRef) (string, error) {
	if mock.GetDiffFunc == nil {
		panic("OrchAPIMock.GetDiffFunc: method is nil but OrchAPI.GetDiff was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ref orchapi.RunRef
	}{
		Ctx: ctx,
		Ref: ref,
	}
	mock.lockGetDiff.Lock()
	mock.calls.GetDiff = append(mock.calls.GetDiff, callInfo)
	mock.lockGetDiff.Unlock()
	return mock.GetDiffFunc(ctx, ref)
}

// GetDiffCalls gets all the calls that were made to GetDiff.
// Check the length with:
//
//	len(mockedOrchAPI.GetDiffCalls())
func (mock *OrchAPIMock) GetDiffCalls() []struct {
	Ctx context.Context
	Ref orchapi.RunRef
} {
	var calls []struct {
		Ctx context.Context
		Ref orchapi.RunRef
	}
	mock.lockGetDiff.RLock()
	calls = mock.calls.GetDiff
	mock.lockGetDiff.RUnlock()
	return calls
}

// GetDiffStats calls GetDiffStatsFunc.
func (mock *OrchAPIMock) GetDiffStats(ctx context.Context, ref orchapi.RunRef) (*orchapi.DiffStats, error) {
	if mock.GetDiffStatsFunc == nil {
		panic("OrchAPIMock.GetDiffStatsFunc: method is nil but OrchAPI.GetDiffStats was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ref orchapi.RunRef
	}{
		Ctx: ctx,
		Ref: ref,
	}
	mock.lockGetDiffStats.Lock()
	mock.calls.GetDiffStats = append(mock.calls.GetDiffStats, callInfo)
	mock.lockGetDiffStats.Unlock()
	return mock.GetDiffStatsFunc(ctx, ref)
}

// GetDiffStatsCalls gets all the calls that were made to GetDiffStats.
// Check the length with:
//
//	len(mockedOrchAPI.GetDiffStatsCalls())
func (mock *OrchAPIMock) GetDiffStatsCalls() []struct {
	Ctx context.Context
	Ref orchapi.RunRef
} {
	var calls []struct {
		Ctx context.Context
		Ref orchapi.RunRef
	}
	mock.lockGetDiffStats.RLock()
	calls = mock.calls.GetDiffStats
	mock.lockGetDiffStats.RUnlock()
	return calls
}

// GetIssue calls GetIssueFunc.
func (mock *OrchAPIMock) GetIssue(ctx context.Context, issueID model.IssueID) (*orchapi.Issue, error) {
	if mock.GetIssueFunc == nil {
		panic("OrchAPIMock.GetIssueFunc: method is nil but OrchAPI.GetIssue was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		IssueID model.IssueID
	}{
		Ctx:     ctx,
		IssueID: issueID,
	}
	mock.lockGetIssue.Lock()
	mock.calls.GetIssue = append(mock.calls.GetIssue, callInfo)
	mock.lockGetIssue.Unlock()
	return mock.GetIssueFunc(ctx, issueID)
}

// GetIssueCalls gets all the calls that were made to GetIssue.
// Check the length with:
//
//	len(mockedOrchAPI.GetIssueCalls())
func (mock *OrchAPIMock) GetIssueCalls() []struct {
	Ctx     context.Context
	IssueID model.IssueID
} {
	var calls []struct {
		Ctx     context.Context
		IssueID model.IssueID
	}
	mock.lockGetIssue.RLock()
	calls = mock.calls.GetIssue
	mock.lockGetIssue.RUnlock()
	return calls
}

// GetLatestRun calls GetLatestRunFunc.
func (mock *OrchAPIMock) GetLatestRun(ctx context.Context, issueID model.IssueID) (*orchapi.Run, error) {
	if mock.GetLatestRunFunc == nil {
		panic("OrchAPIMock.GetLatestRunFunc: method is nil but OrchAPI.GetLatestRun was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		IssueID model.IssueID
	}{
		Ctx:     ctx,
		IssueID: issueID,
	}
	mock.lockGetLatestRun.Lock()
	mock.calls.GetLatestRun = append(mock.calls.GetLatestRun, callInfo)
	mock.lockGetLatestRun.Unlock()
	return mock.GetLatestRunFunc(ctx, issueID)
}

// GetLatestRunCalls gets all the calls that were made to GetLatestRun.
// Check the length with:
//
//	len(mockedOrchAPI.GetLatestRunCalls())
func (mock *OrchAPIMock) GetLatestRunCalls() []struct {
	Ctx     context.Context
	IssueID model.IssueID
} {
	var calls []struct {
		Ctx     context.Context
		IssueID model.IssueID
	}
	mock.lockGetLatestRun.RLock()
	calls = mock.calls.GetLatestRun
	mock.lockGetLatestRun.RUnlock()
	return calls
}

// GetRun calls GetRunFunc.
func (mock *OrchAPIMock) GetRun(ctx context.Context, issueID model.IssueID, runID model.RunID) (*orchapi.Run, error) {
	if mock.GetRunFunc == nil {
		panic("OrchAPIMock.GetRunFunc: method is nil but OrchAPI.GetRun was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		IssueID model.IssueID
		RunID   model.RunID
	}{
		Ctx:     ctx,
		IssueID: issueID,
		RunID:   runID,
	}
	mock.lockGetRun.Lock()
	mock.calls.GetRun = append(mock.calls.GetRun, callInfo)
	mock.lockGetRun.Unlock()
	return mock.GetRunFunc(ctx, issueID, runID)
}

// GetRunCalls gets all the calls that were made to GetRun.
// Check the length with:
//
//	len(mockedOrchAPI.GetRunCalls())
func (mock *OrchAPIMock) GetRunCalls() []struct {
	Ctx     context.Context
	IssueID model.IssueID
	RunID   model.RunID
} {
	var calls []struct {
		Ctx     context.Context
		IssueID model.IssueID
		RunID   model.RunID
	}
	mock.lockGetRun.RLock()
	calls = mock.calls.GetRun
	mock.lockGetRun.RUnlock()
	return calls
}

// InjectInitialPrompt calls InjectInitialPromptFunc.
func (mock *OrchAPIMock) InjectInitialPrompt(ctx context.Context, ref orchapi.RunRef, prompt string) error {
	if mock.InjectInitialPromptFunc == nil {
		panic("OrchAPIMock.InjectInitialPromptFunc: method is nil but OrchAPI.InjectInitialPrompt was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Ref    orchapi.RunRef
		Prompt string
	}{
		Ctx:    ctx,
		Ref:    ref,
		Prompt: prompt,
	}
	mock.lockInjectInitialPrompt.Lock()
	mock.calls.InjectInitialPrompt = append(mock.calls.InjectInitialPrompt, callInfo)
	mock.lockInjectInitialPrompt.Unlock()
	return mock.InjectInitialPromptFunc(ctx, ref, prompt)
}

// InjectInitialPromptCalls gets all the calls that were made to InjectInitialPrompt.
// Check the length with:
//
//	len(mockedOrchAPI.InjectInitialPromptCalls())
func (mock *OrchAPIMock) InjectInitialPromptCalls() []struct {
	Ctx    context.Context
	Ref    orchapi.RunRef
	Prompt string
} {
	var calls []struct {
		Ctx    context.Context
		Ref    orchapi.RunRef
		Prompt string
	}
	mock.lockInjectInitialPrompt.RLock()
	calls = mock.calls.InjectInitialPrompt
	mock.lockInjectInitialPrompt.RUnlock()
	return calls
}

// ListIssues calls ListIssuesFunc.
func (mock *OrchAPIMock) ListIssues(ctx context.Context, filter *orchapi.ListIssuesFilter) (*orchapi.ListIssuesResult, error) {
	if mock.ListIssuesFunc == nil {
		panic("OrchAPIMock.ListIssuesFunc: method is nil but OrchAPI.ListIssues was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Filter *orchapi.ListIssuesFilter
	}{
		Ctx:    ctx,
		Filter: filter,
	}
	mock.lockListIssues.Lock()
	mock.calls.ListIssues = append(mock.calls.ListIssues, callInfo)
	mock.lockListIssues.Unlock()
	return mock.ListIssuesFunc(ctx, filter)
}

// ListIssuesCalls gets all the calls that were made to ListIssues.
// Check the length with:
//
//	len(mockedOrchAPI.ListIssuesCalls())
func (mock *OrchAPIMock) ListIssuesCalls() []struct {
	Ctx    context.Context
	Filter *orchapi.ListIssuesFilter
} {
	var calls []struct {
		Ctx    context.Context
		Filter *orchapi.ListIssuesFilter
	}
	mock.lockListIssues.RLock()
	calls = mock.calls.ListIssues
	mock.lockListIssues.RUnlock()
	return calls
}

// ListRuns calls ListRunsFunc.
func (mock *OrchAPIMock) ListRuns(ctx context.Context, filter *orchapi.ListRunsFilter) (*orchapi.ListRunsResult, error) {
	if mock.ListRunsFunc == nil {
		panic("OrchAPIMock.ListRunsFunc: method is nil but OrchAPI.ListRuns was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Filter *orchapi.ListRunsFilter
	}{
		Ctx:    ctx,
		Filter: filter,
	}
	mock.lockListRuns.Lock()
	mock.calls.ListRuns = append(mock.calls.ListRuns, callInfo)
	mock.lockListRuns.Unlock()
	return mock.ListRunsFunc(ctx, filter)
}

// ListRunsCalls gets all the calls that were made to ListRuns.
// Check the length with:
//
//	len(mockedOrchAPI.ListRunsCalls())
func (mock *OrchAPIMock) ListRunsCalls() []struct {
	Ctx    context.Context
	Filter *orchapi.ListRunsFilter
} {
	var calls []struct {
		Ctx    context.Context
		Filter *orchapi.ListRunsFilter
	}
	mock.lockListRuns.RLock()
	calls = mock.calls.ListRuns
	mock.lockListRuns.RUnlock()
	return calls
}

// MarkRunResolved calls MarkRunResolvedFunc.
func (mock *OrchAPIMock) MarkRunResolved(ctx context.Context, ref orchapi.RunRef) error {
	if mock.MarkRunResolvedFunc == nil {
		panic("OrchAPIMock.MarkRunResolvedFunc: method is nil but OrchAPI.MarkRunResolved was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ref orchapi.RunRef
	}{
		Ctx: ctx,
		Ref: ref,
	}
	mock.lockMarkRunResolved.Lock()
	mock.calls.MarkRunResolved = append(mock.calls.MarkRunResolved, callInfo)
	mock.lockMarkRunResolved.Unlock()
	return mock.MarkRunResolvedFunc(ctx, ref)
}

// MarkRunResolvedCalls gets all the calls that were made to MarkRunResolved.
// Check the length with:
//
//	len(mockedOrchAPI.MarkRunResolvedCalls())
func (mock *OrchAPIMock) MarkRunResolvedCalls() []struct {
	Ctx context.Context
	Ref orchapi.RunRef
} {
	var calls []struct {
		Ctx context.Context
		Ref orchapi.RunRef
	}
	mock.lockMarkRunResolved.RLock()
	calls = mock.calls.MarkRunResolved
	mock.lockMarkRunResolved.RUnlock()
	return calls
}

// Ping calls PingFunc.
func (mock *OrchAPIMock) Ping(ctx context.Context) error {
	if mock.PingFunc == nil {
		panic("OrchAPIMock.PingFunc: method is nil but OrchAPI.Ping was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockPing.Lock()
	mock.calls.Ping = append(mock.calls.Ping, callInfo)
	mock.lockPing.Unlock()
	return mock.PingFunc(ctx)
}

// PingCalls gets all the calls that were made to Ping.
// Check the length with:
//
//	len(mockedOrchAPI.PingCalls())
func (mock *OrchAPIMock) PingCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockPing.RLock()
	calls = mock.calls.Ping
	mock.lockPing.RUnlock()
	return calls
}

// QueryOpenCodeServer calls QueryOpenCodeServerFunc.
func (mock *OrchAPIMock) QueryOpenCodeServer(ctx context.Context, port int) (*orchapi.QueryOpenCodeServerResult, error) {
	if mock.QueryOpenCodeServerFunc == nil {
		panic("OrchAPIMock.QueryOpenCodeServerFunc: method is nil but OrchAPI.QueryOpenCodeServer was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Port int
	}{
		Ctx:  ctx,
		Port: port,
	}
	mock.lockQueryOpenCodeServer.Lock()
	mock.calls.QueryOpenCodeServer = append(mock.calls.QueryOpenCodeServer, callInfo)
	mock.lockQueryOpenCodeServer.Unlock()
	return mock.QueryOpenCodeServerFunc(ctx, port)
}

// QueryOpenCodeServerCalls gets all the calls that were made to QueryOpenCodeServer.
// Check the length with:
//
//	len(mockedOrchAPI.QueryOpenCodeServerCalls())
func (mock *OrchAPIMock) QueryOpenCodeServerCalls() []struct {
	Ctx  context.Context
	Port int
} {
	var calls []struct {
		Ctx  context.Context
		Port int
	}
	mock.lockQueryOpenCodeServer.RLock()
	calls = mock.calls.QueryOpenCodeServer
	mock.lockQueryOpenCodeServer.RUnlock()
	return calls
}

// ReadAgentPrompt calls ReadAgentPromptFunc.
func (mock *OrchAPIMock) ReadAgentPrompt(ctx context.Context, ref orchapi.RunRef) (string, error) {
	if mock.ReadAgentPromptFunc == nil {
		panic("OrchAPIMock.ReadAgentPromptFunc: method is nil but OrchAPI.ReadAgentPrompt was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ref orchapi.RunRef
	}{
		Ctx: ctx,
		Ref: ref,
	}
	mock.lockReadAgentPrompt.Lock()
	mock.calls.ReadAgentPrompt = append(mock.calls.ReadAgentPrompt, callInfo)
	mock.lockReadAgentPrompt.Unlock()
	return mock.ReadAgentPromptFunc(ctx, ref)
}

// ReadAgentPromptCalls gets all the calls that were made to ReadAgentPrompt.
// Check the length with:
//
//	len(mockedOrchAPI.ReadAgentPromptCalls())
func (mock *OrchAPIMock) ReadAgentPromptCalls() []struct {
	Ctx context.Context
	Ref orchapi.RunRef
} {
	var calls []struct {
		Ctx context.Context
		Ref orchapi.RunRef
	}
	mock.lockReadAgentPrompt.RLock()
	calls = mock.calls.ReadAgentPrompt
	mock.lockReadAgentPrompt.RUnlock()
	return calls
}

// ReadFile calls ReadFileFunc.
func (mock *OrchAPIMock) ReadFile(ctx context.Context, path string) ([]byte, error) {
	if mock.ReadFileFunc == nil {
		panic("OrchAPIMock.ReadFileFunc: method is nil but OrchAPI.ReadFile was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
	}{
		Ctx:  ctx,
		Path: path,
	}
	mock.lockReadFile.Lock()
	mock.calls.ReadFile = append(mock.calls.ReadFile, callInfo)
	mock.lockReadFile.Unlock()
	return mock.ReadFileFunc(ctx, path)
}

// ReadFileCalls gets all the calls that were made to ReadFile.
// Check the length with:
//
//	len(mockedOrchAPI.ReadFileCalls())
func (mock *OrchAPIMock) ReadFileCalls() []struct {
	Ctx  context.Context
	Path string
} {
	var calls []struct {
		Ctx  context.Context
		Path string
	}
	mock.lockReadFile.RLock()
	calls = mock.calls.ReadFile
	mock.lockReadFile.RUnlock()
	return calls
}

// RepairState calls RepairStateFunc.
func (mock *OrchAPIMock) RepairState(ctx context.Context, opts *orchapi.RepairOptions) (*orchapi.RepairResult, error) {
	if mock.RepairStateFunc == nil {
		panic("OrchAPIMock.RepairStateFunc: method is nil but OrchAPI.RepairState was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Opts *orchapi.RepairOptions
	}{
		Ctx:  ctx,
		Opts: opts,
	}
	mock.lockRepairState.Lock()
	mock.calls.RepairState = append(mock.calls.RepairState, callInfo)
	mock.lockRepairState.Unlock()
	return mock.RepairStateFunc(ctx, opts)
}

// RepairStateCalls gets all the calls that were made to RepairState.
// Check the length with:
//
//	len(mockedOrchAPI.RepairStateCalls())
func (mock *OrchAPIMock) RepairStateCalls() []struct {
	Ctx  context.Context
	Opts *orchapi.RepairOptions
} {
	var calls []struct {
		Ctx  context.Context
		Opts *orchapi.RepairOptions
	}
	mock.lockRepairState.RLock()
	calls = mock.calls.RepairState
	mock.lockRepairState.RUnlock()
	return calls
}

// ResolveIssue calls ResolveIssueFunc.
func (mock *OrchAPIMock) ResolveIssue(ctx context.Context, issueID model.IssueID, force bool) error {
	if mock.ResolveIssueFunc == nil {
		panic("OrchAPIMock.ResolveIssueFunc: method is nil but OrchAPI.ResolveIssue was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		IssueID model.IssueID
		Force   bool
	}{
		Ctx:     ctx,
		IssueID: issueID,
		Force:   force,
	}
	mock.lockResolveIssue.Lock()
	mock.calls.ResolveIssue = append(mock.calls.ResolveIssue, callInfo)
	mock.lockResolveIssue.Unlock()
	return mock.ResolveIssueFunc(ctx, issueID, force)
}

// ResolveIssueCalls gets all the calls that were made to ResolveIssue.
// Check the length with:
//
//	len(mockedOrchAPI.ResolveIssueCalls())
func (mock *OrchAPIMock) ResolveIssueCalls() []struct {
	Ctx     context.Context
	IssueID model.IssueID
	Force   bool
} {
	var calls []struct {
		Ctx     context.Context
		IssueID model.IssueID
		Force   bool
	}
	mock.lockResolveIssue.RLock()
	calls = mock.calls.ResolveIssue
	mock.lockResolveIssue.RUnlock()
	return calls
}

// ResolveRun calls ResolveRunFunc.
func (mock *OrchAPIMock) ResolveRun(ctx context.Context, ref orchapi.RunRef) (*orchapi.Run, error) {
	if mock.ResolveRunFunc == nil {
		panic("OrchAPIMock.ResolveRunFunc: method is nil but OrchAPI.ResolveRun was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ref orchapi.RunRef
	}{
		Ctx: ctx,
		Ref: ref,
	}
	mock.lockResolveRun.Lock()
	mock.calls.ResolveRun = append(mock.calls.ResolveRun, callInfo)
	mock.lockResolveRun.Unlock()
	return mock.ResolveRunFunc(ctx, ref)
}

// ResolveRunCalls gets all the calls that were made to ResolveRun.
// Check the length with:
//
//	len(mockedOrchAPI.ResolveRunCalls())
func (mock *OrchAPIMock) ResolveRunCalls() []struct {
	Ctx context.Context
	Ref orchapi.RunRef
} {
	var calls []struct {
		Ctx context.Context
		Ref orchapi.RunRef
	}
	mock.lockResolveRun.RLock()
	calls = mock.calls.ResolveRun
	mock.lockResolveRun.RUnlock()
	return calls
}

// SendMessage calls SendMessageFunc.
func (mock *OrchAPIMock) SendMessage(ctx context.Context, ref orchapi.RunRef, message string, noEnter bool) error {
	if mock.SendMessageFunc == nil {
		panic("OrchAPIMock.SendMessageFunc: method is nil but OrchAPI.SendMessage was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Ref     orchapi.RunRef
		Message string
		NoEnter bool
	}{
		Ctx:     ctx,
		Ref:     ref,
		Message: message,
		NoEnter: noEnter,
	}
	mock.lockSendMessage.Lock()
	mock.calls.SendMessage = append(mock.calls.SendMessage, callInfo)
	mock.lockSendMessage.Unlock()
	return mock.SendMessageFunc(ctx, ref, message, noEnter)
}

// SendMessageCalls gets all the calls that were made to SendMessage.
// Check the length with:
//
//	len(mockedOrchAPI.SendMessageCalls())
func (mock *OrchAPIMock) SendMessageCalls() []struct {
	Ctx     context.Context
	Ref     orchapi.RunRef
	Message string
	NoEnter bool
} {
	var calls []struct {
		Ctx     context.Context
		Ref     orchapi.RunRef
		Message string
		NoEnter bool
	}
	mock.lockSendMessage.RLock()
	calls = mock.calls.SendMessage
	mock.lockSendMessage.RUnlock()
	return calls
}

// SetIssueStatus calls SetIssueStatusFunc.
func (mock *OrchAPIMock) SetIssueStatus(ctx context.Context, issueID model.IssueID, status orchapi.IssueStatus) error {
	if mock.SetIssueStatusFunc == nil {
		panic("OrchAPIMock.SetIssueStatusFunc: method is nil but OrchAPI.SetIssueStatus was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		IssueID model.IssueID
		Status  orchapi.IssueStatus
	}{
		Ctx:     ctx,
		IssueID: issueID,
		Status:  status,
	}
	mock.lockSetIssueStatus.Lock()
	mock.calls.SetIssueStatus = append(mock.calls.SetIssueStatus, callInfo)
	mock.lockSetIssueStatus.Unlock()
	return mock.SetIssueStatusFunc(ctx, issueID, status)
}

// SetIssueStatusCalls gets all the calls that were made to SetIssueStatus.
// Check the length with:
//
//	len(mockedOrchAPI.SetIssueStatusCalls())
func (mock *OrchAPIMock) SetIssueStatusCalls() []struct {
	Ctx     context.Context
	IssueID model.IssueID
	Status  orchapi.IssueStatus
} {
	var calls []struct {
		Ctx     context.Context
		IssueID model.IssueID
		Status  orchapi.IssueStatus
	}
	mock.lockSetIssueStatus.RLock()
	calls = mock.calls.SetIssueStatus
	mock.lockSetIssueStatus.RUnlock()
	return calls
}

// StartRun calls StartRunFunc.
func (mock *OrchAPIMock) StartRun(ctx context.Context, req *orchapi.StartRunRequest) (*orchapi.StartRunResult, error) {
	if mock.StartRunFunc == nil {
		panic("OrchAPIMock.StartRunFunc: method is nil but OrchAPI.StartRun was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *orchapi.StartRunRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockStartRun.Lock()
	mock.calls.StartRun = append(mock.calls.StartRun, callInfo)
	mock.lockStartRun.Unlock()
	return mock.StartRunFunc(ctx, req)
}

// StartRunCalls gets all the calls that were made to StartRun.
// Check the length with:
//
//	len(mockedOrchAPI.StartRunCalls())
func (mock *OrchAPIMock) StartRunCalls() []struct {
	Ctx context.Context
	Req *orchapi.StartRunRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *orchapi.StartRunRequest
	}
	mock.lockStartRun.RLock()
	calls = mock.calls.StartRun
	mock.lockStartRun.RUnlock()
	return calls
}

// StopRun calls StopRunFunc.
func (mock *OrchAPIMock) StopRun(ctx context.Context, ref orchapi.RunRef, force bool) (*orchapi.StopRunResult, error) {
	if mock.StopRunFunc == nil {
		panic("OrchAPIMock.StopRunFunc: method is nil but OrchAPI.StopRun was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Ref   orchapi.RunRef
		Force bool
	}{
		Ctx:   ctx,
		Ref:   ref,
		Force: force,
	}
	mock.lockStopRun.Lock()
	mock.calls.StopRun = append(mock.calls.StopRun, callInfo)
	mock.lockStopRun.Unlock()
	return mock.StopRunFunc(ctx, ref, force)
}

// StopRunCalls gets all the calls that were made to StopRun.
// Check the length with:
//
//	len(mockedOrchAPI.StopRunCalls())
func (mock *OrchAPIMock) StopRunCalls() []struct {
	Ctx   context.Context
	Ref   orchapi.RunRef
	Force bool
} {
	var calls []struct {
		Ctx   context.Context
		Ref   orchapi.RunRef
		Force bool
	}
	mock.lockStopRun.RLock()
	calls = mock.calls.StopRun
	mock.lockStopRun.RUnlock()
	return calls
}

// StreamRunEvents calls StreamRunEventsFunc.
func (mock *OrchAPIMock) StreamRunEvents(ctx context.Context, filter *orchapi.RunEventFilter) (orchapi.RunEventStream, error) {
	if mock.StreamRunEventsFunc == nil {
		panic("OrchAPIMock.StreamRunEventsFunc: method is nil but OrchAPI.StreamRunEvents was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Filter *orchapi.RunEventFilter
	}{
		Ctx:    ctx,
		Filter: filter,
	}
	mock.lockStreamRunEvents.Lock()
	mock.calls.StreamRunEvents = append(mock.calls.StreamRunEvents, callInfo)
	mock.lockStreamRunEvents.Unlock()
	return mock.StreamRunEventsFunc(ctx, filter)
}

// StreamRunEventsCalls gets all the calls that were made to StreamRunEvents.
// Check the length with:
//
//	len(mockedOrchAPI.StreamRunEventsCalls())
func (mock *OrchAPIMock) StreamRunEventsCalls() []struct {
	Ctx    context.Context
	Filter *orchapi.RunEventFilter
} {
	var calls []struct {
		Ctx    context.Context
		Filter *orchapi.RunEventFilter
	}
	mock.lockStreamRunEvents.RLock()
	calls = mock.calls.StreamRunEvents
	mock.lockStreamRunEvents.RUnlock()
	return calls
}

// UpdateIssue calls UpdateIssueFunc.
func (mock *OrchAPIMock) UpdateIssue(ctx context.Context, issueID model.IssueID, req *orchapi.UpdateIssueRequest) (*orchapi.Issue, error) {
	if mock.UpdateIssueFunc == nil {
		panic("OrchAPIMock.UpdateIssueFunc: method is nil but OrchAPI.UpdateIssue was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		IssueID model.IssueID
		Req     *orchapi.UpdateIssueRequest
	}{
		Ctx:     ctx,
		IssueID: issueID,
		Req:     req,
	}
	mock.lockUpdateIssue.Lock()
	mock.calls.UpdateIssue = append(mock.calls.UpdateIssue, callInfo)
	mock.lockUpdateIssue.Unlock()
	return mock.UpdateIssueFunc(ctx, issueID, req)
}

// UpdateIssueCalls gets all the calls that were made to UpdateIssue.
// Check the length with:
//
//	len(mockedOrchAPI.UpdateIssueCalls())
func (mock *OrchAPIMock) UpdateIssueCalls() []struct {
	Ctx     context.Context
	IssueID model.IssueID
	Req     *orchapi.UpdateIssueRequest
} {
	var calls []struct {
		Ctx     context.Context
		IssueID model.IssueID
		Req     *orchapi.UpdateIssueRequest
	}
	mock.lockUpdateIssue.RLock()
	calls = mock.calls.UpdateIssue
	mock.lockUpdateIssue.RUnlock()
	return calls
}

// ValidateIssueFiles calls ValidateIssueFilesFunc.
func (mock *OrchAPIMock) ValidateIssueFiles(ctx context.Context, issueID model.IssueID) (*orchapi.ValidateIssueFilesResult, error) {
	if mock.ValidateIssueFilesFunc == nil {
		panic("OrchAPIMock.ValidateIssueFilesFunc: method is nil but OrchAPI.ValidateIssueFiles was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		IssueID model.IssueID
	}{
		Ctx:     ctx,
		IssueID: issueID,
	}
	mock.lockValidateIssueFiles.Lock()
	mock.calls.ValidateIssueFiles = append(mock.calls.ValidateIssueFiles, callInfo)
	mock.lockValidateIssueFiles.Unlock()
	return mock.ValidateIssueFilesFunc(ctx, issueID)
}

// ValidateIssueFilesCalls gets all the calls that were made to ValidateIssueFiles.
// Check the length with:
//
//	len(mockedOrchAPI.ValidateIssueFilesCalls())
func (mock *OrchAPIMock) ValidateIssueFilesCalls() []struct {
	Ctx     context.Context
	IssueID model.IssueID
} {
	var calls []struct {
		Ctx     context.Context
		IssueID model.IssueID
	}
	mock.lockValidateIssueFiles.RLock()
	calls = mock.calls.ValidateIssueFiles
	mock.lockValidateIssueFiles.RUnlock()
	return calls
}

// WaitForRuns calls WaitForRunsFunc.
func (mock *OrchAPIMock) WaitForRuns(ctx context.Context, refs []string, timeoutSeconds int) (*orchapi.WaitForRunsResult, error) {
	if mock.WaitForRunsFunc == nil {
		panic("OrchAPIMock.WaitForRunsFunc: method is nil but OrchAPI.WaitForRuns was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Refs           []string
		TimeoutSeconds int
	}{
		Ctx:            ctx,
		Refs:           refs,
		TimeoutSeconds: timeoutSeconds,
	}
	mock.lockWaitForRuns.Lock()
	mock.calls.WaitForRuns = append(mock.calls.WaitForRuns, callInfo)
	mock.lockWaitForRuns.Unlock()
	return mock.WaitForRunsFunc(ctx, refs, timeoutSeconds)
}

// WaitForRunsCalls gets all the calls that were made to WaitForRuns.
// Check the length with:
//
//	len(mockedOrchAPI.WaitForRunsCalls())
func (mock *OrchAPIMock) WaitForRunsCalls() []struct {
	Ctx            context.Context
	Refs           []string
	TimeoutSeconds int
} {
	var calls []struct {
		Ctx            context.Context
		Refs           []string
		TimeoutSeconds int
	}
	mock.lockWaitForRuns.RLock()
	calls = mock.calls.WaitForRuns
	mock.lockWaitForRuns.RUnlock()
	return calls
}

// WriteAgentPrompt calls WriteAgentPromptFunc.
func (mock *OrchAPIMock) WriteAgentPrompt(ctx context.Context, ref orchapi.RunRef, content string) error {
	if mock.WriteAgentPromptFunc == nil {
		panic("OrchAPIMock.WriteAgentPromptFunc: method is nil but OrchAPI.WriteAgentPrompt was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Ref     orchapi.RunRef
		Content string
	}{
		Ctx:     ctx,
		Ref:     ref,
		Content: content,
	}
	mock.lockWriteAgentPrompt.Lock()
	mock.calls.WriteAgentPrompt = append(mock.calls.WriteAgentPrompt, callInfo)
	mock.lockWriteAgentPrompt.Unlock()
	return mock.WriteAgentPromptFunc(ctx, ref, content)
}

// WriteAgentPromptCalls gets all the calls that were made to WriteAgentPrompt.
// Check the length with:
//
//	len(mockedOrchAPI.WriteAgentPromptCalls())
func (mock *OrchAPIMock) WriteAgentPromptCalls() []struct {
	Ctx     context.Context
	Ref     orchapi.RunRef
	Content string
} {
	var calls []struct {
		Ctx     context.Context
		Ref     orchapi.RunRef
		Content string
	}
	mock.lockWriteAgentPrompt.RLock()
	calls = mock.calls.WriteAgentPrompt
	mock.lockWriteAgentPrompt.RUnlock()
	return calls
}

// WriteFile calls WriteFileFunc.
func (mock *OrchAPIMock) WriteFile(ctx context.Context, path string, content []byte, perm uint32) error {
	if mock.WriteFileFunc == nil {
		panic("OrchAPIMock.WriteFileFunc: method is nil but OrchAPI.WriteFile was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Path    string
		Content []byte
		Perm    uint32
	}{
		Ctx:     ctx,
		Path:    path,
		Content: content,
		Perm:    perm,
	}
	mock.lockWriteFile.Lock()
	mock.calls.WriteFile = append(mock.calls.WriteFile, callInfo)
	mock.lockWriteFile.Unlock()
	return mock.WriteFileFunc(ctx, path, content, perm)
}

// WriteFileCalls gets all the calls that were made to WriteFile.
// Check the length with:
//
//	len(mockedOrchAPI.WriteFileCalls())
func (mock *OrchAPIMock) WriteFileCalls() []struct {
	Ctx     context.Context
	Path    string
	Content []byte
	Perm    uint32
} {
	var calls []struct {
		Ctx     context.Context
		Path    string
		Content []byte
		Perm    uint32
	}
	mock.lockWriteFile.RLock()
	calls = mock.calls.WriteFile
	mock.lockWriteFile.RUnlock()
	return calls
}
