// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package testutil

import (
	"context"
	"github.com/proboscis/orch/internal/git"
	"sync"
)

// Ensure, that RunnerMock does implement git.Runner.
// If this is not the case, regenerate this file with moq.
var _ git.Runner = &RunnerMock{}

// RunnerMock is a mock implementation of git.Runner.
//
//	func TestSomethingThatUsesRunner(t *testing.T) {
//
//		// make and configure a mocked git.Runner
//		mockedRunner := &RunnerMock{
//			CurrentBranchFunc: func(ctx context.Context, workDir string) (string, error) {
//				panic("mock out the CurrentBranch method")
//			},
//			DeleteBranchFunc: func(ctx context.Context, repoRoot string, branch string) error {
//				panic("mock out the DeleteBranch method")
//			},
//			DiffFunc: func(ctx context.Context, workDir string, args ...string) (string, error) {
//				panic("mock out the Diff method")
//			},
//			MergedBranchesFunc: func(ctx context.Context, workDir string, baseBranch string) ([]string, error) {
//				panic("mock out the MergedBranches method")
//			},
//			StatusPorcelainFunc: func(ctx context.Context, workDir string) (string, error) {
//				panic("mock out the StatusPorcelain method")
//			},
//		}
//
//		// use mockedRunner in code that requires git.Runner
//		// and then make assertions.
//
//	}
type RunnerMock struct {
	// CurrentBranchFunc mocks the CurrentBranch method.
	CurrentBranchFunc func(ctx context.Context, workDir string) (string, error)

	// DeleteBranchFunc mocks the DeleteBranch method.
	DeleteBranchFunc func(ctx context.Context, repoRoot string, branch string) error

	// DiffFunc mocks the Diff method.
	DiffFunc func(ctx context.Context, workDir string, args ...string) (string, error)

	// MergedBranchesFunc mocks the MergedBranches method.
	MergedBranchesFunc func(ctx context.Context, workDir string, baseBranch string) ([]string, error)

	// StatusPorcelainFunc mocks the StatusPorcelain method.
	StatusPorcelainFunc func(ctx context.Context, workDir string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// CurrentBranch holds details about calls to the CurrentBranch method.
		CurrentBranch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkDir is the workDir argument value.
			WorkDir string
		}
		// DeleteBranch holds details about calls to the DeleteBranch method.
		DeleteBranch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoRoot is the repoRoot argument value.
			RepoRoot string
			// Branch is the branch argument value.
			Branch string
		}
		// Diff holds details about calls to the Diff method.
		Diff []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkDir is the workDir argument value.
			WorkDir string
			// Args is the args argument value.
			Args []string
		}
		// MergedBranches holds details about calls to the MergedBranches method.
		MergedBranches []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkDir is the workDir argument value.
			WorkDir string
			// BaseBranch is the baseBranch argument value.
			BaseBranch string
		}
		// StatusPorcelain holds details about calls to the StatusPorcelain method.
		StatusPorcelain []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkDir is the workDir argument value.
			WorkDir string
		}
	}
	lockCurrentBranch   sync.RWMutex
	lockDeleteBranch    sync.RWMutex
	lockDiff            sync.RWMutex
	lockMergedBranches  sync.RWMutex
	lockStatusPorcelain sync.RWMutex
}

// CurrentBranch calls CurrentBranchFunc.
func (mock *RunnerMock) CurrentBranch(ctx context.Context, workDir string) (string, error) {
	if mock.CurrentBranchFunc == nil {
		panic("RunnerMock.CurrentBranchFunc: method is nil but Runner.CurrentBranch was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		WorkDir string
	}{
		Ctx:     ctx,
		WorkDir: workDir,
	}
	mock.lockCurrentBranch.Lock()
	mock.calls.CurrentBranch = append(mock.calls.CurrentBranch, callInfo)
	mock.lockCurrentBranch.Unlock()
	return mock.CurrentBranchFunc(ctx, workDir)
}

// CurrentBranchCalls gets all the calls that were made to CurrentBranch.
// Check the length with:
//
//	len(mockedRunner.CurrentBranchCalls())
func (mock *RunnerMock) CurrentBranchCalls() []struct {
	Ctx     context.Context
	WorkDir string
} {
	var calls []struct {
		Ctx     context.Context
		WorkDir string
	}
	mock.lockCurrentBranch.RLock()
	calls = mock.calls.CurrentBranch
	mock.lockCurrentBranch.RUnlock()
	return calls
}

// DeleteBranch calls DeleteBranchFunc.
func (mock *RunnerMock) DeleteBranch(ctx context.Context, repoRoot string, branch string) error {
	if mock.DeleteBranchFunc == nil {
		panic("RunnerMock.DeleteBranchFunc: method is nil but Runner.DeleteBranch was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		RepoRoot string
		Branch   string
	}{
		Ctx:      ctx,
		RepoRoot: repoRoot,
		Branch:   branch,
	}
	mock.lockDeleteBranch.Lock()
	mock.calls.DeleteBranch = append(mock.calls.DeleteBranch, callInfo)
	mock.lockDeleteBranch.Unlock()
	return mock.DeleteBranchFunc(ctx, repoRoot, branch)
}

// DeleteBranchCalls gets all the calls that were made to DeleteBranch.
// Check the length with:
//
//	len(mockedRunner.DeleteBranchCalls())
func (mock *RunnerMock) DeleteBranchCalls() []struct {
	Ctx      context.Context
	RepoRoot string
	Branch   string
} {
	var calls []struct {
		Ctx      context.Context
		RepoRoot string
		Branch   string
	}
	mock.lockDeleteBranch.RLock()
	calls = mock.calls.DeleteBranch
	mock.lockDeleteBranch.RUnlock()
	return calls
}

// Diff calls DiffFunc.
func (mock *RunnerMock) Diff(ctx context.Context, workDir string, args ...string) (string, error) {
	if mock.DiffFunc == nil {
		panic("RunnerMock.DiffFunc: method is nil but Runner.Diff was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		WorkDir string
		Args    []string
	}{
		Ctx:     ctx,
		WorkDir: workDir,
		Args:    args,
	}
	mock.lockDiff.Lock()
	mock.calls.Diff = append(mock.calls.Diff, callInfo)
	mock.lockDiff.Unlock()
	return mock.DiffFunc(ctx, workDir, args...)
}

// DiffCalls gets all the calls that were made to Diff.
// Check the length with:
//
//	len(mockedRunner.DiffCalls())
func (mock *RunnerMock) DiffCalls() []struct {
	Ctx     context.Context
	WorkDir string
	Args    []string
} {
	var calls []struct {
		Ctx     context.Context
		WorkDir string
		Args    []string
	}
	mock.lockDiff.RLock()
	calls = mock.calls.Diff
	mock.lockDiff.RUnlock()
	return calls
}

// MergedBranches calls MergedBranchesFunc.
func (mock *RunnerMock) MergedBranches(ctx context.Context, workDir string, baseBranch string) ([]string, error) {
	if mock.MergedBranchesFunc == nil {
		panic("RunnerMock.MergedBranchesFunc: method is nil but Runner.MergedBranches was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		WorkDir    string
		BaseBranch string
	}{
		Ctx:        ctx,
		WorkDir:    workDir,
		BaseBranch: baseBranch,
	}
	mock.lockMergedBranches.Lock()
	mock.calls.MergedBranches = append(mock.calls.MergedBranches, callInfo)
	mock.lockMergedBranches.Unlock()
	return mock.MergedBranchesFunc(ctx, workDir, baseBranch)
}

// MergedBranchesCalls gets all the calls that were made to MergedBranches.
// Check the length with:
//
//	len(mockedRunner.MergedBranchesCalls())
func (mock *RunnerMock) MergedBranchesCalls() []struct {
	Ctx        context.Context
	WorkDir    string
	BaseBranch string
} {
	var calls []struct {
		Ctx        context.Context
		WorkDir    string
		BaseBranch string
	}
	mock.lockMergedBranches.RLock()
	calls = mock.calls.MergedBranches
	mock.lockMergedBranches.RUnlock()
	return calls
}

// StatusPorcelain calls StatusPorcelainFunc.
func (mock *RunnerMock) StatusPorcelain(ctx context.Context, workDir string) (string, error) {
	if mock.StatusPorcelainFunc == nil {
		panic("RunnerMock.StatusPorcelainFunc: method is nil but Runner.StatusPorcelain was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		WorkDir string
	}{
		Ctx:     ctx,
		WorkDir: workDir,
	}
	mock.lockStatusPorcelain.Lock()
	mock.calls.StatusPorcelain = append(mock.calls.StatusPorcelain, callInfo)
	mock.lockStatusPorcelain.Unlock()
	return mock.StatusPorcelainFunc(ctx, workDir)
}

// StatusPorcelainCalls gets all the calls that were made to StatusPorcelain.
// Check the length with:
//
//	len(mockedRunner.StatusPorcelainCalls())
func (mock *RunnerMock) StatusPorcelainCalls() []struct {
	Ctx     context.Context
	WorkDir string
} {
	var calls []struct {
		Ctx     context.Context
		WorkDir string
	}
	mock.lockStatusPorcelain.RLock()
	calls = mock.calls.StatusPorcelain
	mock.lockStatusPorcelain.RUnlock()
	return calls
}
