// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package testutil

import (
	"github.com/s22625/orch/internal/multiplexer"
	"sync"
	"time"
)

// Ensure, that MultiplexerMock does implement multiplexer.Multiplexer.
// If this is not the case, regenerate this file with moq.
var _ multiplexer.Multiplexer = &MultiplexerMock{}

// MultiplexerMock is a mock implementation of multiplexer.Multiplexer.
//
//	func TestSomethingThatUsesMultiplexer(t *testing.T) {
//
//		// make and configure a mocked multiplexer.Multiplexer
//		mockedMultiplexer := &MultiplexerMock{
//			AgentAliveFunc: func(session string, paneCommands map[string][]string) (bool, bool) {
//				panic("mock out the AgentAlive method")
//			},
//			AttachSessionFunc: func(session string) error {
//				panic("mock out the AttachSession method")
//			},
//			CapturePaneFunc: func(session string, lines int) (string, error) {
//				panic("mock out the CapturePane method")
//			},
//			CurrentSessionFunc: func() (string, error) {
//				panic("mock out the CurrentSession method")
//			},
//			GetOptionFunc: func(session string, option string) (string, error) {
//				panic("mock out the GetOption method")
//			},
//			HasSessionFunc: func(name string) bool {
//				panic("mock out the HasSession method")
//			},
//			IsAvailableFunc: func() bool {
//				panic("mock out the IsAvailable method")
//			},
//			IsInsideSessionFunc: func() bool {
//				panic("mock out the IsInsideSession method")
//			},
//			KillPaneFunc: func(target string) error {
//				panic("mock out the KillPane method")
//			},
//			KillSessionFunc: func(session string) error {
//				panic("mock out the KillSession method")
//			},
//			LinkWindowFunc: func(sourceSession string, sourceWindow int, targetSession string, targetIndex int) error {
//				panic("mock out the LinkWindow method")
//			},
//			LinkWindowByIDFunc: func(windowID string, targetSession string, targetIndex int) error {
//				panic("mock out the LinkWindowByID method")
//			},
//			ListPaneCommandsFunc: func() (map[string][]string, error) {
//				panic("mock out the ListPaneCommands method")
//			},
//			ListPanesFunc: func(target string) ([]multiplexer.Pane, error) {
//				panic("mock out the ListPanes method")
//			},
//			ListSessionsFunc: func() ([]string, error) {
//				panic("mock out the ListSessions method")
//			},
//			ListWindowsFunc: func(session string) ([]multiplexer.Window, error) {
//				panic("mock out the ListWindows method")
//			},
//			NewSessionFunc: func(cfg *multiplexer.SessionConfig) error {
//				panic("mock out the NewSession method")
//			},
//			NewWindowFunc: func(session string, name string, workDir string, command string) error {
//				panic("mock out the NewWindow method")
//			},
//			RenameWindowFunc: func(session string, index int, name string) error {
//				panic("mock out the RenameWindow method")
//			},
//			SelectPaneFunc: func(target string) error {
//				panic("mock out the SelectPane method")
//			},
//			SelectWindowFunc: func(session string, index int) error {
//				panic("mock out the SelectWindow method")
//			},
//			SelectWindowByIDFunc: func(windowID string) error {
//				panic("mock out the SelectWindowByID method")
//			},
//			SendKeysFunc: func(session string, keys string) error {
//				panic("mock out the SendKeys method")
//			},
//			SendKeysLiteralFunc: func(session string, keys string) error {
//				panic("mock out the SendKeysLiteral method")
//			},
//			SendTextFunc: func(session string, text string) error {
//				panic("mock out the SendText method")
//			},
//			SetOptionFunc: func(session string, option string, value string) error {
//				panic("mock out the SetOption method")
//			},
//			SetPaneTitleFunc: func(target string, title string) error {
//				panic("mock out the SetPaneTitle method")
//			},
//			SplitWindowFunc: func(target string, vertical bool, percent int) (string, error) {
//				panic("mock out the SplitWindow method")
//			},
//			SwapPaneFunc: func(source string, target string) error {
//				panic("mock out the SwapPane method")
//			},
//			SwitchClientFunc: func(session string) error {
//				panic("mock out the SwitchClient method")
//			},
//			TypeFunc: func() multiplexer.Type {
//				panic("mock out the Type method")
//			},
//			UnlinkWindowFunc: func(session string, index int) error {
//				panic("mock out the UnlinkWindow method")
//			},
//			WaitForReadyFunc: func(session string, pattern string, timeout time.Duration) error {
//				panic("mock out the WaitForReady method")
//			},
//		}
//
//		// use mockedMultiplexer in code that requires multiplexer.Multiplexer
//		// and then make assertions.
//
//	}
type MultiplexerMock struct {
	// AgentAliveFunc mocks the AgentAlive method.
	AgentAliveFunc func(session string, paneCommands map[string][]string) (bool, bool)

	// AttachSessionFunc mocks the AttachSession method.
	AttachSessionFunc func(session string) error

	// CapturePaneFunc mocks the CapturePane method.
	CapturePaneFunc func(session string, lines int) (string, error)

	// CurrentSessionFunc mocks the CurrentSession method.
	CurrentSessionFunc func() (string, error)

	// GetOptionFunc mocks the GetOption method.
	GetOptionFunc func(session string, option string) (string, error)

	// HasSessionFunc mocks the HasSession method.
	HasSessionFunc func(name string) bool

	// IsAvailableFunc mocks the IsAvailable method.
	IsAvailableFunc func() bool

	// IsInsideSessionFunc mocks the IsInsideSession method.
	IsInsideSessionFunc func() bool

	// KillPaneFunc mocks the KillPane method.
	KillPaneFunc func(target string) error

	// KillSessionFunc mocks the KillSession method.
	KillSessionFunc func(session string) error

	// LinkWindowFunc mocks the LinkWindow method.
	LinkWindowFunc func(sourceSession string, sourceWindow int, targetSession string, targetIndex int) error

	// LinkWindowByIDFunc mocks the LinkWindowByID method.
	LinkWindowByIDFunc func(windowID string, targetSession string, targetIndex int) error

	// ListPaneCommandsFunc mocks the ListPaneCommands method.
	ListPaneCommandsFunc func() (map[string][]string, error)

	// ListPanesFunc mocks the ListPanes method.
	ListPanesFunc func(target string) ([]multiplexer.Pane, error)

	// ListSessionsFunc mocks the ListSessions method.
	ListSessionsFunc func() ([]string, error)

	// ListWindowsFunc mocks the ListWindows method.
	ListWindowsFunc func(session string) ([]multiplexer.Window, error)

	// NewSessionFunc mocks the NewSession method.
	NewSessionFunc func(cfg *multiplexer.SessionConfig) error

	// NewWindowFunc mocks the NewWindow method.
	NewWindowFunc func(session string, name string, workDir string, command string) error

	// RenameWindowFunc mocks the RenameWindow method.
	RenameWindowFunc func(session string, index int, name string) error

	// SelectPaneFunc mocks the SelectPane method.
	SelectPaneFunc func(target string) error

	// SelectWindowFunc mocks the SelectWindow method.
	SelectWindowFunc func(session string, index int) error

	// SelectWindowByIDFunc mocks the SelectWindowByID method.
	SelectWindowByIDFunc func(windowID string) error

	// SendKeysFunc mocks the SendKeys method.
	SendKeysFunc func(session string, keys string) error

	// SendKeysLiteralFunc mocks the SendKeysLiteral method.
	SendKeysLiteralFunc func(session string, keys string) error

	// SendTextFunc mocks the SendText method.
	SendTextFunc func(session string, text string) error

	// SetOptionFunc mocks the SetOption method.
	SetOptionFunc func(session string, option string, value string) error

	// SetPaneTitleFunc mocks the SetPaneTitle method.
	SetPaneTitleFunc func(target string, title string) error

	// SplitWindowFunc mocks the SplitWindow method.
	SplitWindowFunc func(target string, vertical bool, percent int) (string, error)

	// SwapPaneFunc mocks the SwapPane method.
	SwapPaneFunc func(source string, target string) error

	// SwitchClientFunc mocks the SwitchClient method.
	SwitchClientFunc func(session string) error

	// TypeFunc mocks the Type method.
	TypeFunc func() multiplexer.Type

	// UnlinkWindowFunc mocks the UnlinkWindow method.
	UnlinkWindowFunc func(session string, index int) error

	// WaitForReadyFunc mocks the WaitForReady method.
	WaitForReadyFunc func(session string, pattern string, timeout time.Duration) error

	// calls tracks calls to the methods.
	calls struct {
		// AgentAlive holds details about calls to the AgentAlive method.
		AgentAlive []struct {
			// Session is the session argument value.
			Session string
			// PaneCommands is the paneCommands argument value.
			PaneCommands map[string][]string
		}
		// AttachSession holds details about calls to the AttachSession method.
		AttachSession []struct {
			// Session is the session argument value.
			Session string
		}
		// CapturePane holds details about calls to the CapturePane method.
		CapturePane []struct {
			// Session is the session argument value.
			Session string
			// Lines is the lines argument value.
			Lines int
		}
		// CurrentSession holds details about calls to the CurrentSession method.
		CurrentSession []struct {
		}
		// GetOption holds details about calls to the GetOption method.
		GetOption []struct {
			// Session is the session argument value.
			Session string
			// Option is the option argument value.
			Option string
		}
		// HasSession holds details about calls to the HasSession method.
		HasSession []struct {
			// Name is the name argument value.
			Name string
		}
		// IsAvailable holds details about calls to the IsAvailable method.
		IsAvailable []struct {
		}
		// IsInsideSession holds details about calls to the IsInsideSession method.
		IsInsideSession []struct {
		}
		// KillPane holds details about calls to the KillPane method.
		KillPane []struct {
			// Target is the target argument value.
			Target string
		}
		// KillSession holds details about calls to the KillSession method.
		KillSession []struct {
			// Session is the session argument value.
			Session string
		}
		// LinkWindow holds details about calls to the LinkWindow method.
		LinkWindow []struct {
			// SourceSession is the sourceSession argument value.
			SourceSession string
			// SourceWindow is the sourceWindow argument value.
			SourceWindow int
			// TargetSession is the targetSession argument value.
			TargetSession string
			// TargetIndex is the targetIndex argument value.
			TargetIndex int
		}
		// LinkWindowByID holds details about calls to the LinkWindowByID method.
		LinkWindowByID []struct {
			// WindowID is the windowID argument value.
			WindowID string
			// TargetSession is the targetSession argument value.
			TargetSession string
			// TargetIndex is the targetIndex argument value.
			TargetIndex int
		}
		// ListPaneCommands holds details about calls to the ListPaneCommands method.
		ListPaneCommands []struct {
		}
		// ListPanes holds details about calls to the ListPanes method.
		ListPanes []struct {
			// Target is the target argument value.
			Target string
		}
		// ListSessions holds details about calls to the ListSessions method.
		ListSessions []struct {
		}
		// ListWindows holds details about calls to the ListWindows method.
		ListWindows []struct {
			// Session is the session argument value.
			Session string
		}
		// NewSession holds details about calls to the NewSession method.
		NewSession []struct {
			// Cfg is the cfg argument value.
			Cfg *multiplexer.SessionConfig
		}
		// NewWindow holds details about calls to the NewWindow method.
		NewWindow []struct {
			// Session is the session argument value.
			Session string
			// Name is the name argument value.
			Name string
			// WorkDir is the workDir argument value.
			WorkDir string
			// Command is the command argument value.
			Command string
		}
		// RenameWindow holds details about calls to the RenameWindow method.
		RenameWindow []struct {
			// Session is the session argument value.
			Session string
			// Index is the index argument value.
			Index int
			// Name is the name argument value.
			Name string
		}
		// SelectPane holds details about calls to the SelectPane method.
		SelectPane []struct {
			// Target is the target argument value.
			Target string
		}
		// SelectWindow holds details about calls to the SelectWindow method.
		SelectWindow []struct {
			// Session is the session argument value.
			Session string
			// Index is the index argument value.
			Index int
		}
		// SelectWindowByID holds details about calls to the SelectWindowByID method.
		SelectWindowByID []struct {
			// WindowID is the windowID argument value.
			WindowID string
		}
		// SendKeys holds details about calls to the SendKeys method.
		SendKeys []struct {
			// Session is the session argument value.
			Session string
			// Keys is the keys argument value.
			Keys string
		}
		// SendKeysLiteral holds details about calls to the SendKeysLiteral method.
		SendKeysLiteral []struct {
			// Session is the session argument value.
			Session string
			// Keys is the keys argument value.
			Keys string
		}
		// SendText holds details about calls to the SendText method.
		SendText []struct {
			// Session is the session argument value.
			Session string
			// Text is the text argument value.
			Text string
		}
		// SetOption holds details about calls to the SetOption method.
		SetOption []struct {
			// Session is the session argument value.
			Session string
			// Option is the option argument value.
			Option string
			// Value is the value argument value.
			Value string
		}
		// SetPaneTitle holds details about calls to the SetPaneTitle method.
		SetPaneTitle []struct {
			// Target is the target argument value.
			Target string
			// Title is the title argument value.
			Title string
		}
		// SplitWindow holds details about calls to the SplitWindow method.
		SplitWindow []struct {
			// Target is the target argument value.
			Target string
			// Vertical is the vertical argument value.
			Vertical bool
			// Percent is the percent argument value.
			Percent int
		}
		// SwapPane holds details about calls to the SwapPane method.
		SwapPane []struct {
			// Source is the source argument value.
			Source string
			// Target is the target argument value.
			Target string
		}
		// SwitchClient holds details about calls to the SwitchClient method.
		SwitchClient []struct {
			// Session is the session argument value.
			Session string
		}
		// Type holds details about calls to the Type method.
		Type []struct {
		}
		// UnlinkWindow holds details about calls to the UnlinkWindow method.
		UnlinkWindow []struct {
			// Session is the session argument value.
			Session string
			// Index is the index argument value.
			Index int
		}
		// WaitForReady holds details about calls to the WaitForReady method.
		WaitForReady []struct {
			// Session is the session argument value.
			Session string
			// Pattern is the pattern argument value.
			Pattern string
			// Timeout is the timeout argument value.
			Timeout time.Duration
		}
	}
	lockAgentAlive       sync.RWMutex
	lockAttachSession    sync.RWMutex
	lockCapturePane      sync.RWMutex
	lockCurrentSession   sync.RWMutex
	lockGetOption        sync.RWMutex
	lockHasSession       sync.RWMutex
	lockIsAvailable      sync.RWMutex
	lockIsInsideSession  sync.RWMutex
	lockKillPane         sync.RWMutex
	lockKillSession      sync.RWMutex
	lockLinkWindow       sync.RWMutex
	lockLinkWindowByID   sync.RWMutex
	lockListPaneCommands sync.RWMutex
	lockListPanes        sync.RWMutex
	lockListSessions     sync.RWMutex
	lockListWindows      sync.RWMutex
	lockNewSession       sync.RWMutex
	lockNewWindow        sync.RWMutex
	lockRenameWindow     sync.RWMutex
	lockSelectPane       sync.RWMutex
	lockSelectWindow     sync.RWMutex
	lockSelectWindowByID sync.RWMutex
	lockSendKeys         sync.RWMutex
	lockSendKeysLiteral  sync.RWMutex
	lockSendText         sync.RWMutex
	lockSetOption        sync.RWMutex
	lockSetPaneTitle     sync.RWMutex
	lockSplitWindow      sync.RWMutex
	lockSwapPane         sync.RWMutex
	lockSwitchClient     sync.RWMutex
	lockType             sync.RWMutex
	lockUnlinkWindow     sync.RWMutex
	lockWaitForReady     sync.RWMutex
}

// AgentAlive calls AgentAliveFunc.
func (mock *MultiplexerMock) AgentAlive(session string, paneCommands map[string][]string) (bool, bool) {
	if mock.AgentAliveFunc == nil {
		panic("MultiplexerMock.AgentAliveFunc: method is nil but Multiplexer.AgentAlive was just called")
	}
	callInfo := struct {
		Session      string
		PaneCommands map[string][]string
	}{
		Session:      session,
		PaneCommands: paneCommands,
	}
	mock.lockAgentAlive.Lock()
	mock.calls.AgentAlive = append(mock.calls.AgentAlive, callInfo)
	mock.lockAgentAlive.Unlock()
	return mock.AgentAliveFunc(session, paneCommands)
}

// AgentAliveCalls gets all the calls that were made to AgentAlive.
// Check the length with:
//
//	len(mockedMultiplexer.AgentAliveCalls())
func (mock *MultiplexerMock) AgentAliveCalls() []struct {
	Session      string
	PaneCommands map[string][]string
} {
	var calls []struct {
		Session      string
		PaneCommands map[string][]string
	}
	mock.lockAgentAlive.RLock()
	calls = mock.calls.AgentAlive
	mock.lockAgentAlive.RUnlock()
	return calls
}

// AttachSession calls AttachSessionFunc.
func (mock *MultiplexerMock) AttachSession(session string) error {
	if mock.AttachSessionFunc == nil {
		panic("MultiplexerMock.AttachSessionFunc: method is nil but Multiplexer.AttachSession was just called")
	}
	callInfo := struct {
		Session string
	}{
		Session: session,
	}
	mock.lockAttachSession.Lock()
	mock.calls.AttachSession = append(mock.calls.AttachSession, callInfo)
	mock.lockAttachSession.Unlock()
	return mock.AttachSessionFunc(session)
}

// AttachSessionCalls gets all the calls that were made to AttachSession.
// Check the length with:
//
//	len(mockedMultiplexer.AttachSessionCalls())
func (mock *MultiplexerMock) AttachSessionCalls() []struct {
	Session string
} {
	var calls []struct {
		Session string
	}
	mock.lockAttachSession.RLock()
	calls = mock.calls.AttachSession
	mock.lockAttachSession.RUnlock()
	return calls
}

// CapturePane calls CapturePaneFunc.
func (mock *MultiplexerMock) CapturePane(session string, lines int) (string, error) {
	if mock.CapturePaneFunc == nil {
		panic("MultiplexerMock.CapturePaneFunc: method is nil but Multiplexer.CapturePane was just called")
	}
	callInfo := struct {
		Session string
		Lines   int
	}{
		Session: session,
		Lines:   lines,
	}
	mock.lockCapturePane.Lock()
	mock.calls.CapturePane = append(mock.calls.CapturePane, callInfo)
	mock.lockCapturePane.Unlock()
	return mock.CapturePaneFunc(session, lines)
}

// CapturePaneCalls gets all the calls that were made to CapturePane.
// Check the length with:
//
//	len(mockedMultiplexer.CapturePaneCalls())
func (mock *MultiplexerMock) CapturePaneCalls() []struct {
	Session string
	Lines   int
} {
	var calls []struct {
		Session string
		Lines   int
	}
	mock.lockCapturePane.RLock()
	calls = mock.calls.CapturePane
	mock.lockCapturePane.RUnlock()
	return calls
}

// CurrentSession calls CurrentSessionFunc.
func (mock *MultiplexerMock) CurrentSession() (string, error) {
	if mock.CurrentSessionFunc == nil {
		panic("MultiplexerMock.CurrentSessionFunc: method is nil but Multiplexer.CurrentSession was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCurrentSession.Lock()
	mock.calls.CurrentSession = append(mock.calls.CurrentSession, callInfo)
	mock.lockCurrentSession.Unlock()
	return mock.CurrentSessionFunc()
}

// CurrentSessionCalls gets all the calls that were made to CurrentSession.
// Check the length with:
//
//	len(mockedMultiplexer.CurrentSessionCalls())
func (mock *MultiplexerMock) CurrentSessionCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCurrentSession.RLock()
	calls = mock.calls.CurrentSession
	mock.lockCurrentSession.RUnlock()
	return calls
}

// GetOption calls GetOptionFunc.
func (mock *MultiplexerMock) GetOption(session string, option string) (string, error) {
	if mock.GetOptionFunc == nil {
		panic("MultiplexerMock.GetOptionFunc: method is nil but Multiplexer.GetOption was just called")
	}
	callInfo := struct {
		Session string
		Option  string
	}{
		Session: session,
		Option:  option,
	}
	mock.lockGetOption.Lock()
	mock.calls.GetOption = append(mock.calls.GetOption, callInfo)
	mock.lockGetOption.Unlock()
	return mock.GetOptionFunc(session, option)
}

// GetOptionCalls gets all the calls that were made to GetOption.
// Check the length with:
//
//	len(mockedMultiplexer.GetOptionCalls())
func (mock *MultiplexerMock) GetOptionCalls() []struct {
	Session string
	Option  string
} {
	var calls []struct {
		Session string
		Option  string
	}
	mock.lockGetOption.RLock()
	calls = mock.calls.GetOption
	mock.lockGetOption.RUnlock()
	return calls
}

// HasSession calls HasSessionFunc.
func (mock *MultiplexerMock) HasSession(name string) bool {
	if mock.HasSessionFunc == nil {
		panic("MultiplexerMock.HasSessionFunc: method is nil but Multiplexer.HasSession was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockHasSession.Lock()
	mock.calls.HasSession = append(mock.calls.HasSession, callInfo)
	mock.lockHasSession.Unlock()
	return mock.HasSessionFunc(name)
}

// HasSessionCalls gets all the calls that were made to HasSession.
// Check the length with:
//
//	len(mockedMultiplexer.HasSessionCalls())
func (mock *MultiplexerMock) HasSessionCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockHasSession.RLock()
	calls = mock.calls.HasSession
	mock.lockHasSession.RUnlock()
	return calls
}

// IsAvailable calls IsAvailableFunc.
func (mock *MultiplexerMock) IsAvailable() bool {
	if mock.IsAvailableFunc == nil {
		panic("MultiplexerMock.IsAvailableFunc: method is nil but Multiplexer.IsAvailable was just called")
	}
	callInfo := struct {
	}{}
	mock.lockIsAvailable.Lock()
	mock.calls.IsAvailable = append(mock.calls.IsAvailable, callInfo)
	mock.lockIsAvailable.Unlock()
	return mock.IsAvailableFunc()
}

// IsAvailableCalls gets all the calls that were made to IsAvailable.
// Check the length with:
//
//	len(mockedMultiplexer.IsAvailableCalls())
func (mock *MultiplexerMock) IsAvailableCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIsAvailable.RLock()
	calls = mock.calls.IsAvailable
	mock.lockIsAvailable.RUnlock()
	return calls
}

// IsInsideSession calls IsInsideSessionFunc.
func (mock *MultiplexerMock) IsInsideSession() bool {
	if mock.IsInsideSessionFunc == nil {
		panic("MultiplexerMock.IsInsideSessionFunc: method is nil but Multiplexer.IsInsideSession was just called")
	}
	callInfo := struct {
	}{}
	mock.lockIsInsideSession.Lock()
	mock.calls.IsInsideSession = append(mock.calls.IsInsideSession, callInfo)
	mock.lockIsInsideSession.Unlock()
	return mock.IsInsideSessionFunc()
}

// IsInsideSessionCalls gets all the calls that were made to IsInsideSession.
// Check the length with:
//
//	len(mockedMultiplexer.IsInsideSessionCalls())
func (mock *MultiplexerMock) IsInsideSessionCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIsInsideSession.RLock()
	calls = mock.calls.IsInsideSession
	mock.lockIsInsideSession.RUnlock()
	return calls
}

// KillPane calls KillPaneFunc.
func (mock *MultiplexerMock) KillPane(target string) error {
	if mock.KillPaneFunc == nil {
		panic("MultiplexerMock.KillPaneFunc: method is nil but Multiplexer.KillPane was just called")
	}
	callInfo := struct {
		Target string
	}{
		Target: target,
	}
	mock.lockKillPane.Lock()
	mock.calls.KillPane = append(mock.calls.KillPane, callInfo)
	mock.lockKillPane.Unlock()
	return mock.KillPaneFunc(target)
}

// KillPaneCalls gets all the calls that were made to KillPane.
// Check the length with:
//
//	len(mockedMultiplexer.KillPaneCalls())
func (mock *MultiplexerMock) KillPaneCalls() []struct {
	Target string
} {
	var calls []struct {
		Target string
	}
	mock.lockKillPane.RLock()
	calls = mock.calls.KillPane
	mock.lockKillPane.RUnlock()
	return calls
}

// KillSession calls KillSessionFunc.
func (mock *MultiplexerMock) KillSession(session string) error {
	if mock.KillSessionFunc == nil {
		panic("MultiplexerMock.KillSessionFunc: method is nil but Multiplexer.KillSession was just called")
	}
	callInfo := struct {
		Session string
	}{
		Session: session,
	}
	mock.lockKillSession.Lock()
	mock.calls.KillSession = append(mock.calls.KillSession, callInfo)
	mock.lockKillSession.Unlock()
	return mock.KillSessionFunc(session)
}

// KillSessionCalls gets all the calls that were made to KillSession.
// Check the length with:
//
//	len(mockedMultiplexer.KillSessionCalls())
func (mock *MultiplexerMock) KillSessionCalls() []struct {
	Session string
} {
	var calls []struct {
		Session string
	}
	mock.lockKillSession.RLock()
	calls = mock.calls.KillSession
	mock.lockKillSession.RUnlock()
	return calls
}

// LinkWindow calls LinkWindowFunc.
func (mock *MultiplexerMock) LinkWindow(sourceSession string, sourceWindow int, targetSession string, targetIndex int) error {
	if mock.LinkWindowFunc == nil {
		panic("MultiplexerMock.LinkWindowFunc: method is nil but Multiplexer.LinkWindow was just called")
	}
	callInfo := struct {
		SourceSession string
		SourceWindow  int
		TargetSession string
		TargetIndex   int
	}{
		SourceSession: sourceSession,
		SourceWindow:  sourceWindow,
		TargetSession: targetSession,
		TargetIndex:   targetIndex,
	}
	mock.lockLinkWindow.Lock()
	mock.calls.LinkWindow = append(mock.calls.LinkWindow, callInfo)
	mock.lockLinkWindow.Unlock()
	return mock.LinkWindowFunc(sourceSession, sourceWindow, targetSession, targetIndex)
}

// LinkWindowCalls gets all the calls that were made to LinkWindow.
// Check the length with:
//
//	len(mockedMultiplexer.LinkWindowCalls())
func (mock *MultiplexerMock) LinkWindowCalls() []struct {
	SourceSession string
	SourceWindow  int
	TargetSession string
	TargetIndex   int
} {
	var calls []struct {
		SourceSession string
		SourceWindow  int
		TargetSession string
		TargetIndex   int
	}
	mock.lockLinkWindow.RLock()
	calls = mock.calls.LinkWindow
	mock.lockLinkWindow.RUnlock()
	return calls
}

// LinkWindowByID calls LinkWindowByIDFunc.
func (mock *MultiplexerMock) LinkWindowByID(windowID string, targetSession string, targetIndex int) error {
	if mock.LinkWindowByIDFunc == nil {
		panic("MultiplexerMock.LinkWindowByIDFunc: method is nil but Multiplexer.LinkWindowByID was just called")
	}
	callInfo := struct {
		WindowID      string
		TargetSession string
		TargetIndex   int
	}{
		WindowID:      windowID,
		TargetSession: targetSession,
		TargetIndex:   targetIndex,
	}
	mock.lockLinkWindowByID.Lock()
	mock.calls.LinkWindowByID = append(mock.calls.LinkWindowByID, callInfo)
	mock.lockLinkWindowByID.Unlock()
	return mock.LinkWindowByIDFunc(windowID, targetSession, targetIndex)
}

// LinkWindowByIDCalls gets all the calls that were made to LinkWindowByID.
// Check the length with:
//
//	len(mockedMultiplexer.LinkWindowByIDCalls())
func (mock *MultiplexerMock) LinkWindowByIDCalls() []struct {
	WindowID      string
	TargetSession string
	TargetIndex   int
} {
	var calls []struct {
		WindowID      string
		TargetSession string
		TargetIndex   int
	}
	mock.lockLinkWindowByID.RLock()
	calls = mock.calls.LinkWindowByID
	mock.lockLinkWindowByID.RUnlock()
	return calls
}

// ListPaneCommands calls ListPaneCommandsFunc.
func (mock *MultiplexerMock) ListPaneCommands() (map[string][]string, error) {
	if mock.ListPaneCommandsFunc == nil {
		panic("MultiplexerMock.ListPaneCommandsFunc: method is nil but Multiplexer.ListPaneCommands was just called")
	}
	callInfo := struct {
	}{}
	mock.lockListPaneCommands.Lock()
	mock.calls.ListPaneCommands = append(mock.calls.ListPaneCommands, callInfo)
	mock.lockListPaneCommands.Unlock()
	return mock.ListPaneCommandsFunc()
}

// ListPaneCommandsCalls gets all the calls that were made to ListPaneCommands.
// Check the length with:
//
//	len(mockedMultiplexer.ListPaneCommandsCalls())
func (mock *MultiplexerMock) ListPaneCommandsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockListPaneCommands.RLock()
	calls = mock.calls.ListPaneCommands
	mock.lockListPaneCommands.RUnlock()
	return calls
}

// ListPanes calls ListPanesFunc.
func (mock *MultiplexerMock) ListPanes(target string) ([]multiplexer.Pane, error) {
	if mock.ListPanesFunc == nil {
		panic("MultiplexerMock.ListPanesFunc: method is nil but Multiplexer.ListPanes was just called")
	}
	callInfo := struct {
		Target string
	}{
		Target: target,
	}
	mock.lockListPanes.Lock()
	mock.calls.ListPanes = append(mock.calls.ListPanes, callInfo)
	mock.lockListPanes.Unlock()
	return mock.ListPanesFunc(target)
}

// ListPanesCalls gets all the calls that were made to ListPanes.
// Check the length with:
//
//	len(mockedMultiplexer.ListPanesCalls())
func (mock *MultiplexerMock) ListPanesCalls() []struct {
	Target string
} {
	var calls []struct {
		Target string
	}
	mock.lockListPanes.RLock()
	calls = mock.calls.ListPanes
	mock.lockListPanes.RUnlock()
	return calls
}

// ListSessions calls ListSessionsFunc.
func (mock *MultiplexerMock) ListSessions() ([]string, error) {
	if mock.ListSessionsFunc == nil {
		panic("MultiplexerMock.ListSessionsFunc: method is nil but Multiplexer.ListSessions was just called")
	}
	callInfo := struct {
	}{}
	mock.lockListSessions.Lock()
	mock.calls.ListSessions = append(mock.calls.ListSessions, callInfo)
	mock.lockListSessions.Unlock()
	return mock.ListSessionsFunc()
}

// ListSessionsCalls gets all the calls that were made to ListSessions.
// Check the length with:
//
//	len(mockedMultiplexer.ListSessionsCalls())
func (mock *MultiplexerMock) ListSessionsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockListSessions.RLock()
	calls = mock.calls.ListSessions
	mock.lockListSessions.RUnlock()
	return calls
}

// ListWindows calls ListWindowsFunc.
func (mock *MultiplexerMock) ListWindows(session string) ([]multiplexer.Window, error) {
	if mock.ListWindowsFunc == nil {
		panic("MultiplexerMock.ListWindowsFunc: method is nil but Multiplexer.ListWindows was just called")
	}
	callInfo := struct {
		Session string
	}{
		Session: session,
	}
	mock.lockListWindows.Lock()
	mock.calls.ListWindows = append(mock.calls.ListWindows, callInfo)
	mock.lockListWindows.Unlock()
	return mock.ListWindowsFunc(session)
}

// ListWindowsCalls gets all the calls that were made to ListWindows.
// Check the length with:
//
//	len(mockedMultiplexer.ListWindowsCalls())
func (mock *MultiplexerMock) ListWindowsCalls() []struct {
	Session string
} {
	var calls []struct {
		Session string
	}
	mock.lockListWindows.RLock()
	calls = mock.calls.ListWindows
	mock.lockListWindows.RUnlock()
	return calls
}

// NewSession calls NewSessionFunc.
func (mock *MultiplexerMock) NewSession(cfg *multiplexer.SessionConfig) error {
	if mock.NewSessionFunc == nil {
		panic("MultiplexerMock.NewSessionFunc: method is nil but Multiplexer.NewSession was just called")
	}
	callInfo := struct {
		Cfg *multiplexer.SessionConfig
	}{
		Cfg: cfg,
	}
	mock.lockNewSession.Lock()
	mock.calls.NewSession = append(mock.calls.NewSession, callInfo)
	mock.lockNewSession.Unlock()
	return mock.NewSessionFunc(cfg)
}

// NewSessionCalls gets all the calls that were made to NewSession.
// Check the length with:
//
//	len(mockedMultiplexer.NewSessionCalls())
func (mock *MultiplexerMock) NewSessionCalls() []struct {
	Cfg *multiplexer.SessionConfig
} {
	var calls []struct {
		Cfg *multiplexer.SessionConfig
	}
	mock.lockNewSession.RLock()
	calls = mock.calls.NewSession
	mock.lockNewSession.RUnlock()
	return calls
}

// NewWindow calls NewWindowFunc.
func (mock *MultiplexerMock) NewWindow(session string, name string, workDir string, command string) error {
	if mock.NewWindowFunc == nil {
		panic("MultiplexerMock.NewWindowFunc: method is nil but Multiplexer.NewWindow was just called")
	}
	callInfo := struct {
		Session string
		Name    string
		WorkDir string
		Command string
	}{
		Session: session,
		Name:    name,
		WorkDir: workDir,
		Command: command,
	}
	mock.lockNewWindow.Lock()
	mock.calls.NewWindow = append(mock.calls.NewWindow, callInfo)
	mock.lockNewWindow.Unlock()
	return mock.NewWindowFunc(session, name, workDir, command)
}

// NewWindowCalls gets all the calls that were made to NewWindow.
// Check the length with:
//
//	len(mockedMultiplexer.NewWindowCalls())
func (mock *MultiplexerMock) NewWindowCalls() []struct {
	Session string
	Name    string
	WorkDir string
	Command string
} {
	var calls []struct {
		Session string
		Name    string
		WorkDir string
		Command string
	}
	mock.lockNewWindow.RLock()
	calls = mock.calls.NewWindow
	mock.lockNewWindow.RUnlock()
	return calls
}

// RenameWindow calls RenameWindowFunc.
func (mock *MultiplexerMock) RenameWindow(session string, index int, name string) error {
	if mock.RenameWindowFunc == nil {
		panic("MultiplexerMock.RenameWindowFunc: method is nil but Multiplexer.RenameWindow was just called")
	}
	callInfo := struct {
		Session string
		Index   int
		Name    string
	}{
		Session: session,
		Index:   index,
		Name:    name,
	}
	mock.lockRenameWindow.Lock()
	mock.calls.RenameWindow = append(mock.calls.RenameWindow, callInfo)
	mock.lockRenameWindow.Unlock()
	return mock.RenameWindowFunc(session, index, name)
}

// RenameWindowCalls gets all the calls that were made to RenameWindow.
// Check the length with:
//
//	len(mockedMultiplexer.RenameWindowCalls())
func (mock *MultiplexerMock) RenameWindowCalls() []struct {
	Session string
	Index   int
	Name    string
} {
	var calls []struct {
		Session string
		Index   int
		Name    string
	}
	mock.lockRenameWindow.RLock()
	calls = mock.calls.RenameWindow
	mock.lockRenameWindow.RUnlock()
	return calls
}

// SelectPane calls SelectPaneFunc.
func (mock *MultiplexerMock) SelectPane(target string) error {
	if mock.SelectPaneFunc == nil {
		panic("MultiplexerMock.SelectPaneFunc: method is nil but Multiplexer.SelectPane was just called")
	}
	callInfo := struct {
		Target string
	}{
		Target: target,
	}
	mock.lockSelectPane.Lock()
	mock.calls.SelectPane = append(mock.calls.SelectPane, callInfo)
	mock.lockSelectPane.Unlock()
	return mock.SelectPaneFunc(target)
}

// SelectPaneCalls gets all the calls that were made to SelectPane.
// Check the length with:
//
//	len(mockedMultiplexer.SelectPaneCalls())
func (mock *MultiplexerMock) SelectPaneCalls() []struct {
	Target string
} {
	var calls []struct {
		Target string
	}
	mock.lockSelectPane.RLock()
	calls = mock.calls.SelectPane
	mock.lockSelectPane.RUnlock()
	return calls
}

// SelectWindow calls SelectWindowFunc.
func (mock *MultiplexerMock) SelectWindow(session string, index int) error {
	if mock.SelectWindowFunc == nil {
		panic("MultiplexerMock.SelectWindowFunc: method is nil but Multiplexer.SelectWindow was just called")
	}
	callInfo := struct {
		Session string
		Index   int
	}{
		Session: session,
		Index:   index,
	}
	mock.lockSelectWindow.Lock()
	mock.calls.SelectWindow = append(mock.calls.SelectWindow, callInfo)
	mock.lockSelectWindow.Unlock()
	return mock.SelectWindowFunc(session, index)
}

// SelectWindowCalls gets all the calls that were made to SelectWindow.
// Check the length with:
//
//	len(mockedMultiplexer.SelectWindowCalls())
func (mock *MultiplexerMock) SelectWindowCalls() []struct {
	Session string
	Index   int
} {
	var calls []struct {
		Session string
		Index   int
	}
	mock.lockSelectWindow.RLock()
	calls = mock.calls.SelectWindow
	mock.lockSelectWindow.RUnlock()
	return calls
}

// SelectWindowByID calls SelectWindowByIDFunc.
func (mock *MultiplexerMock) SelectWindowByID(windowID string) error {
	if mock.SelectWindowByIDFunc == nil {
		panic("MultiplexerMock.SelectWindowByIDFunc: method is nil but Multiplexer.SelectWindowByID was just called")
	}
	callInfo := struct {
		WindowID string
	}{
		WindowID: windowID,
	}
	mock.lockSelectWindowByID.Lock()
	mock.calls.SelectWindowByID = append(mock.calls.SelectWindowByID, callInfo)
	mock.lockSelectWindowByID.Unlock()
	return mock.SelectWindowByIDFunc(windowID)
}

// SelectWindowByIDCalls gets all the calls that were made to SelectWindowByID.
// Check the length with:
//
//	len(mockedMultiplexer.SelectWindowByIDCalls())
func (mock *MultiplexerMock) SelectWindowByIDCalls() []struct {
	WindowID string
} {
	var calls []struct {
		WindowID string
	}
	mock.lockSelectWindowByID.RLock()
	calls = mock.calls.SelectWindowByID
	mock.lockSelectWindowByID.RUnlock()
	return calls
}

// SendKeys calls SendKeysFunc.
func (mock *MultiplexerMock) SendKeys(session string, keys string) error {
	if mock.SendKeysFunc == nil {
		panic("MultiplexerMock.SendKeysFunc: method is nil but Multiplexer.SendKeys was just called")
	}
	callInfo := struct {
		Session string
		Keys    string
	}{
		Session: session,
		Keys:    keys,
	}
	mock.lockSendKeys.Lock()
	mock.calls.SendKeys = append(mock.calls.SendKeys, callInfo)
	mock.lockSendKeys.Unlock()
	return mock.SendKeysFunc(session, keys)
}

// SendKeysCalls gets all the calls that were made to SendKeys.
// Check the length with:
//
//	len(mockedMultiplexer.SendKeysCalls())
func (mock *MultiplexerMock) SendKeysCalls() []struct {
	Session string
	Keys    string
} {
	var calls []struct {
		Session string
		Keys    string
	}
	mock.lockSendKeys.RLock()
	calls = mock.calls.SendKeys
	mock.lockSendKeys.RUnlock()
	return calls
}

// SendKeysLiteral calls SendKeysLiteralFunc.
func (mock *MultiplexerMock) SendKeysLiteral(session string, keys string) error {
	if mock.SendKeysLiteralFunc == nil {
		panic("MultiplexerMock.SendKeysLiteralFunc: method is nil but Multiplexer.SendKeysLiteral was just called")
	}
	callInfo := struct {
		Session string
		Keys    string
	}{
		Session: session,
		Keys:    keys,
	}
	mock.lockSendKeysLiteral.Lock()
	mock.calls.SendKeysLiteral = append(mock.calls.SendKeysLiteral, callInfo)
	mock.lockSendKeysLiteral.Unlock()
	return mock.SendKeysLiteralFunc(session, keys)
}

// SendKeysLiteralCalls gets all the calls that were made to SendKeysLiteral.
// Check the length with:
//
//	len(mockedMultiplexer.SendKeysLiteralCalls())
func (mock *MultiplexerMock) SendKeysLiteralCalls() []struct {
	Session string
	Keys    string
} {
	var calls []struct {
		Session string
		Keys    string
	}
	mock.lockSendKeysLiteral.RLock()
	calls = mock.calls.SendKeysLiteral
	mock.lockSendKeysLiteral.RUnlock()
	return calls
}

// SendText calls SendTextFunc.
func (mock *MultiplexerMock) SendText(session string, text string) error {
	if mock.SendTextFunc == nil {
		panic("MultiplexerMock.SendTextFunc: method is nil but Multiplexer.SendText was just called")
	}
	callInfo := struct {
		Session string
		Text    string
	}{
		Session: session,
		Text:    text,
	}
	mock.lockSendText.Lock()
	mock.calls.SendText = append(mock.calls.SendText, callInfo)
	mock.lockSendText.Unlock()
	return mock.SendTextFunc(session, text)
}

// SendTextCalls gets all the calls that were made to SendText.
// Check the length with:
//
//	len(mockedMultiplexer.SendTextCalls())
func (mock *MultiplexerMock) SendTextCalls() []struct {
	Session string
	Text    string
} {
	var calls []struct {
		Session string
		Text    string
	}
	mock.lockSendText.RLock()
	calls = mock.calls.SendText
	mock.lockSendText.RUnlock()
	return calls
}

// SetOption calls SetOptionFunc.
func (mock *MultiplexerMock) SetOption(session string, option string, value string) error {
	if mock.SetOptionFunc == nil {
		panic("MultiplexerMock.SetOptionFunc: method is nil but Multiplexer.SetOption was just called")
	}
	callInfo := struct {
		Session string
		Option  string
		Value   string
	}{
		Session: session,
		Option:  option,
		Value:   value,
	}
	mock.lockSetOption.Lock()
	mock.calls.SetOption = append(mock.calls.SetOption, callInfo)
	mock.lockSetOption.Unlock()
	return mock.SetOptionFunc(session, option, value)
}

// SetOptionCalls gets all the calls that were made to SetOption.
// Check the length with:
//
//	len(mockedMultiplexer.SetOptionCalls())
func (mock *MultiplexerMock) SetOptionCalls() []struct {
	Session string
	Option  string
	Value   string
} {
	var calls []struct {
		Session string
		Option  string
		Value   string
	}
	mock.lockSetOption.RLock()
	calls = mock.calls.SetOption
	mock.lockSetOption.RUnlock()
	return calls
}

// SetPaneTitle calls SetPaneTitleFunc.
func (mock *MultiplexerMock) SetPaneTitle(target string, title string) error {
	if mock.SetPaneTitleFunc == nil {
		panic("MultiplexerMock.SetPaneTitleFunc: method is nil but Multiplexer.SetPaneTitle was just called")
	}
	callInfo := struct {
		Target string
		Title  string
	}{
		Target: target,
		Title:  title,
	}
	mock.lockSetPaneTitle.Lock()
	mock.calls.SetPaneTitle = append(mock.calls.SetPaneTitle, callInfo)
	mock.lockSetPaneTitle.Unlock()
	return mock.SetPaneTitleFunc(target, title)
}

// SetPaneTitleCalls gets all the calls that were made to SetPaneTitle.
// Check the length with:
//
//	len(mockedMultiplexer.SetPaneTitleCalls())
func (mock *MultiplexerMock) SetPaneTitleCalls() []struct {
	Target string
	Title  string
} {
	var calls []struct {
		Target string
		Title  string
	}
	mock.lockSetPaneTitle.RLock()
	calls = mock.calls.SetPaneTitle
	mock.lockSetPaneTitle.RUnlock()
	return calls
}

// SplitWindow calls SplitWindowFunc.
func (mock *MultiplexerMock) SplitWindow(target string, vertical bool, percent int) (string, error) {
	if mock.SplitWindowFunc == nil {
		panic("MultiplexerMock.SplitWindowFunc: method is nil but Multiplexer.SplitWindow was just called")
	}
	callInfo := struct {
		Target   string
		Vertical bool
		Percent  int
	}{
		Target:   target,
		Vertical: vertical,
		Percent:  percent,
	}
	mock.lockSplitWindow.Lock()
	mock.calls.SplitWindow = append(mock.calls.SplitWindow, callInfo)
	mock.lockSplitWindow.Unlock()
	return mock.SplitWindowFunc(target, vertical, percent)
}

// SplitWindowCalls gets all the calls that were made to SplitWindow.
// Check the length with:
//
//	len(mockedMultiplexer.SplitWindowCalls())
func (mock *MultiplexerMock) SplitWindowCalls() []struct {
	Target   string
	Vertical bool
	Percent  int
} {
	var calls []struct {
		Target   string
		Vertical bool
		Percent  int
	}
	mock.lockSplitWindow.RLock()
	calls = mock.calls.SplitWindow
	mock.lockSplitWindow.RUnlock()
	return calls
}

// SwapPane calls SwapPaneFunc.
func (mock *MultiplexerMock) SwapPane(source string, target string) error {
	if mock.SwapPaneFunc == nil {
		panic("MultiplexerMock.SwapPaneFunc: method is nil but Multiplexer.SwapPane was just called")
	}
	callInfo := struct {
		Source string
		Target string
	}{
		Source: source,
		Target: target,
	}
	mock.lockSwapPane.Lock()
	mock.calls.SwapPane = append(mock.calls.SwapPane, callInfo)
	mock.lockSwapPane.Unlock()
	return mock.SwapPaneFunc(source, target)
}

// SwapPaneCalls gets all the calls that were made to SwapPane.
// Check the length with:
//
//	len(mockedMultiplexer.SwapPaneCalls())
func (mock *MultiplexerMock) SwapPaneCalls() []struct {
	Source string
	Target string
} {
	var calls []struct {
		Source string
		Target string
	}
	mock.lockSwapPane.RLock()
	calls = mock.calls.SwapPane
	mock.lockSwapPane.RUnlock()
	return calls
}

// SwitchClient calls SwitchClientFunc.
func (mock *MultiplexerMock) SwitchClient(session string) error {
	if mock.SwitchClientFunc == nil {
		panic("MultiplexerMock.SwitchClientFunc: method is nil but Multiplexer.SwitchClient was just called")
	}
	callInfo := struct {
		Session string
	}{
		Session: session,
	}
	mock.lockSwitchClient.Lock()
	mock.calls.SwitchClient = append(mock.calls.SwitchClient, callInfo)
	mock.lockSwitchClient.Unlock()
	return mock.SwitchClientFunc(session)
}

// SwitchClientCalls gets all the calls that were made to SwitchClient.
// Check the length with:
//
//	len(mockedMultiplexer.SwitchClientCalls())
func (mock *MultiplexerMock) SwitchClientCalls() []struct {
	Session string
} {
	var calls []struct {
		Session string
	}
	mock.lockSwitchClient.RLock()
	calls = mock.calls.SwitchClient
	mock.lockSwitchClient.RUnlock()
	return calls
}

// Type calls TypeFunc.
func (mock *MultiplexerMock) Type() multiplexer.Type {
	if mock.TypeFunc == nil {
		panic("MultiplexerMock.TypeFunc: method is nil but Multiplexer.Type was just called")
	}
	callInfo := struct {
	}{}
	mock.lockType.Lock()
	mock.calls.Type = append(mock.calls.Type, callInfo)
	mock.lockType.Unlock()
	return mock.TypeFunc()
}

// TypeCalls gets all the calls that were made to Type.
// Check the length with:
//
//	len(mockedMultiplexer.TypeCalls())
func (mock *MultiplexerMock) TypeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockType.RLock()
	calls = mock.calls.Type
	mock.lockType.RUnlock()
	return calls
}

// UnlinkWindow calls UnlinkWindowFunc.
func (mock *MultiplexerMock) UnlinkWindow(session string, index int) error {
	if mock.UnlinkWindowFunc == nil {
		panic("MultiplexerMock.UnlinkWindowFunc: method is nil but Multiplexer.UnlinkWindow was just called")
	}
	callInfo := struct {
		Session string
		Index   int
	}{
		Session: session,
		Index:   index,
	}
	mock.lockUnlinkWindow.Lock()
	mock.calls.UnlinkWindow = append(mock.calls.UnlinkWindow, callInfo)
	mock.lockUnlinkWindow.Unlock()
	return mock.UnlinkWindowFunc(session, index)
}

// UnlinkWindowCalls gets all the calls that were made to UnlinkWindow.
// Check the length with:
//
//	len(mockedMultiplexer.UnlinkWindowCalls())
func (mock *MultiplexerMock) UnlinkWindowCalls() []struct {
	Session string
	Index   int
} {
	var calls []struct {
		Session string
		Index   int
	}
	mock.lockUnlinkWindow.RLock()
	calls = mock.calls.UnlinkWindow
	mock.lockUnlinkWindow.RUnlock()
	return calls
}

// WaitForReady calls WaitForReadyFunc.
func (mock *MultiplexerMock) WaitForReady(session string, pattern string, timeout time.Duration) error {
	if mock.WaitForReadyFunc == nil {
		panic("MultiplexerMock.WaitForReadyFunc: method is nil but Multiplexer.WaitForReady was just called")
	}
	callInfo := struct {
		Session string
		Pattern string
		Timeout time.Duration
	}{
		Session: session,
		Pattern: pattern,
		Timeout: timeout,
	}
	mock.lockWaitForReady.Lock()
	mock.calls.WaitForReady = append(mock.calls.WaitForReady, callInfo)
	mock.lockWaitForReady.Unlock()
	return mock.WaitForReadyFunc(session, pattern, timeout)
}

// WaitForReadyCalls gets all the calls that were made to WaitForReady.
// Check the length with:
//
//	len(mockedMultiplexer.WaitForReadyCalls())
func (mock *MultiplexerMock) WaitForReadyCalls() []struct {
	Session string
	Pattern string
	Timeout time.Duration
} {
	var calls []struct {
		Session string
		Pattern string
		Timeout time.Duration
	}
	mock.lockWaitForReady.RLock()
	calls = mock.calls.WaitForReady
	mock.lockWaitForReady.RUnlock()
	return calls
}
