// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package testutil

import (
	"github.com/proboscis/orch/internal/github"
	"sync"
)

// Ensure, that ClientMock does implement github.Client.
// If this is not the case, regenerate this file with moq.
var _ github.Client = &ClientMock{}

// ClientMock is a mock implementation of github.Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked github.Client
//		mockedClient := &ClientMock{
//			IsAvailableFunc: func() bool {
//				panic("mock out the IsAvailable method")
//			},
//			RunFunc: func(args ...string) ([]byte, error) {
//				panic("mock out the Run method")
//			},
//			RunInDirFunc: func(dir string, args ...string) ([]byte, error) {
//				panic("mock out the RunInDir method")
//			},
//		}
//
//		// use mockedClient in code that requires github.Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// IsAvailableFunc mocks the IsAvailable method.
	IsAvailableFunc func() bool

	// RunFunc mocks the Run method.
	RunFunc func(args ...string) ([]byte, error)

	// RunInDirFunc mocks the RunInDir method.
	RunInDirFunc func(dir string, args ...string) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// IsAvailable holds details about calls to the IsAvailable method.
		IsAvailable []struct {
		}
		// Run holds details about calls to the Run method.
		Run []struct {
			// Args is the args argument value.
			Args []string
		}
		// RunInDir holds details about calls to the RunInDir method.
		RunInDir []struct {
			// Dir is the dir argument value.
			Dir string
			// Args is the args argument value.
			Args []string
		}
	}
	lockIsAvailable sync.RWMutex
	lockRun         sync.RWMutex
	lockRunInDir    sync.RWMutex
}

// IsAvailable calls IsAvailableFunc.
func (mock *ClientMock) IsAvailable() bool {
	if mock.IsAvailableFunc == nil {
		panic("ClientMock.IsAvailableFunc: method is nil but Client.IsAvailable was just called")
	}
	callInfo := struct {
	}{}
	mock.lockIsAvailable.Lock()
	mock.calls.IsAvailable = append(mock.calls.IsAvailable, callInfo)
	mock.lockIsAvailable.Unlock()
	return mock.IsAvailableFunc()
}

// IsAvailableCalls gets all the calls that were made to IsAvailable.
// Check the length with:
//
//	len(mockedClient.IsAvailableCalls())
func (mock *ClientMock) IsAvailableCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIsAvailable.RLock()
	calls = mock.calls.IsAvailable
	mock.lockIsAvailable.RUnlock()
	return calls
}

// Run calls RunFunc.
func (mock *ClientMock) Run(args ...string) ([]byte, error) {
	if mock.RunFunc == nil {
		panic("ClientMock.RunFunc: method is nil but Client.Run was just called")
	}
	callInfo := struct {
		Args []string
	}{
		Args: args,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(args...)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedClient.RunCalls())
func (mock *ClientMock) RunCalls() []struct {
	Args []string
} {
	var calls []struct {
		Args []string
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}

// RunInDir calls RunInDirFunc.
func (mock *ClientMock) RunInDir(dir string, args ...string) ([]byte, error) {
	if mock.RunInDirFunc == nil {
		panic("ClientMock.RunInDirFunc: method is nil but Client.RunInDir was just called")
	}
	callInfo := struct {
		Dir  string
		Args []string
	}{
		Dir:  dir,
		Args: args,
	}
	mock.lockRunInDir.Lock()
	mock.calls.RunInDir = append(mock.calls.RunInDir, callInfo)
	mock.lockRunInDir.Unlock()
	return mock.RunInDirFunc(dir, args...)
}

// RunInDirCalls gets all the calls that were made to RunInDir.
// Check the length with:
//
//	len(mockedClient.RunInDirCalls())
func (mock *ClientMock) RunInDirCalls() []struct {
	Dir  string
	Args []string
} {
	var calls []struct {
		Dir  string
		Args []string
	}
	mock.lockRunInDir.RLock()
	calls = mock.calls.RunInDir
	mock.lockRunInDir.RUnlock()
	return calls
}
