// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/s22625/orch/internal/git"
	"sync"
)

// Ensure, that RunnerMock does implement git.Runner.
// If this is not the case, regenerate this file with moq.
var _ git.Runner = &RunnerMock{}

// RunnerMock is a mock implementation of git.Runner.
//
//	func TestSomethingThatUsesRunner(t *testing.T) {
//
//		// make and configure a mocked git.Runner
//		mockedRunner := &RunnerMock{
//			BranchFunc: func(ctx context.Context, repoDir string) (string, error) {
//				panic("mock out the Branch method")
//			},
//			DeleteBranchFunc: func(ctx context.Context, repoDir string, branch string) error {
//				panic("mock out the DeleteBranch method")
//			},
//			DiffFunc: func(ctx context.Context, repoDir string, args ...string) (string, error) {
//				panic("mock out the Diff method")
//			},
//			ListMergedBranchesFunc: func(ctx context.Context, repoDir string, baseBranch string) ([]string, error) {
//				panic("mock out the ListMergedBranches method")
//			},
//			StatusFunc: func(ctx context.Context, repoDir string) (string, error) {
//				panic("mock out the Status method")
//			},
//		}
//
//		// use mockedRunner in code that requires git.Runner
//		// and then make assertions.
//
//	}
type RunnerMock struct {
	// BranchFunc mocks the Branch method.
	BranchFunc func(ctx context.Context, repoDir string) (string, error)

	// DeleteBranchFunc mocks the DeleteBranch method.
	DeleteBranchFunc func(ctx context.Context, repoDir string, branch string) error

	// DiffFunc mocks the Diff method.
	DiffFunc func(ctx context.Context, repoDir string, args ...string) (string, error)

	// ListMergedBranchesFunc mocks the ListMergedBranches method.
	ListMergedBranchesFunc func(ctx context.Context, repoDir string, baseBranch string) ([]string, error)

	// StatusFunc mocks the Status method.
	StatusFunc func(ctx context.Context, repoDir string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Branch holds details about calls to the Branch method.
		Branch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoDir is the repoDir argument value.
			RepoDir string
		}
		// DeleteBranch holds details about calls to the DeleteBranch method.
		DeleteBranch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoDir is the repoDir argument value.
			RepoDir string
			// Branch is the branch argument value.
			Branch string
		}
		// Diff holds details about calls to the Diff method.
		Diff []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoDir is the repoDir argument value.
			RepoDir string
			// Args is the args argument value.
			Args []string
		}
		// ListMergedBranches holds details about calls to the ListMergedBranches method.
		ListMergedBranches []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoDir is the repoDir argument value.
			RepoDir string
			// BaseBranch is the baseBranch argument value.
			BaseBranch string
		}
		// Status holds details about calls to the Status method.
		Status []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoDir is the repoDir argument value.
			RepoDir string
		}
	}
	lockBranch             sync.RWMutex
	lockDeleteBranch       sync.RWMutex
	lockDiff               sync.RWMutex
	lockListMergedBranches sync.RWMutex
	lockStatus             sync.RWMutex
}

// Branch calls BranchFunc.
func (mock *RunnerMock) Branch(ctx context.Context, repoDir string) (string, error) {
	if mock.BranchFunc == nil {
		panic("RunnerMock.BranchFunc: method is nil but Runner.Branch was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		RepoDir string
	}{
		Ctx:     ctx,
		RepoDir: repoDir,
	}
	mock.lockBranch.Lock()
	mock.calls.Branch = append(mock.calls.Branch, callInfo)
	mock.lockBranch.Unlock()
	return mock.BranchFunc(ctx, repoDir)
}

// BranchCalls gets all the calls that were made to Branch.
// Check the length with:
//
//	len(mockedRunner.BranchCalls())
func (mock *RunnerMock) BranchCalls() []struct {
	Ctx     context.Context
	RepoDir string
} {
	var calls []struct {
		Ctx     context.Context
		RepoDir string
	}
	mock.lockBranch.RLock()
	calls = mock.calls.Branch
	mock.lockBranch.RUnlock()
	return calls
}

// DeleteBranch calls DeleteBranchFunc.
func (mock *RunnerMock) DeleteBranch(ctx context.Context, repoDir string, branch string) error {
	if mock.DeleteBranchFunc == nil {
		panic("RunnerMock.DeleteBranchFunc: method is nil but Runner.DeleteBranch was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		RepoDir string
		Branch  string
	}{
		Ctx:     ctx,
		RepoDir: repoDir,
		Branch:  branch,
	}
	mock.lockDeleteBranch.Lock()
	mock.calls.DeleteBranch = append(mock.calls.DeleteBranch, callInfo)
	mock.lockDeleteBranch.Unlock()
	return mock.DeleteBranchFunc(ctx, repoDir, branch)
}

// DeleteBranchCalls gets all the calls that were made to DeleteBranch.
// Check the length with:
//
//	len(mockedRunner.DeleteBranchCalls())
func (mock *RunnerMock) DeleteBranchCalls() []struct {
	Ctx     context.Context
	RepoDir string
	Branch  string
} {
	var calls []struct {
		Ctx     context.Context
		RepoDir string
		Branch  string
	}
	mock.lockDeleteBranch.RLock()
	calls = mock.calls.DeleteBranch
	mock.lockDeleteBranch.RUnlock()
	return calls
}

// Diff calls DiffFunc.
func (mock *RunnerMock) Diff(ctx context.Context, repoDir string, args ...string) (string, error) {
	if mock.DiffFunc == nil {
		panic("RunnerMock.DiffFunc: method is nil but Runner.Diff was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		RepoDir string
		Args    []string
	}{
		Ctx:     ctx,
		RepoDir: repoDir,
		Args:    args,
	}
	mock.lockDiff.Lock()
	mock.calls.Diff = append(mock.calls.Diff, callInfo)
	mock.lockDiff.Unlock()
	return mock.DiffFunc(ctx, repoDir, args...)
}

// DiffCalls gets all the calls that were made to Diff.
// Check the length with:
//
//	len(mockedRunner.DiffCalls())
func (mock *RunnerMock) DiffCalls() []struct {
	Ctx     context.Context
	RepoDir string
	Args    []string
} {
	var calls []struct {
		Ctx     context.Context
		RepoDir string
		Args    []string
	}
	mock.lockDiff.RLock()
	calls = mock.calls.Diff
	mock.lockDiff.RUnlock()
	return calls
}

// ListMergedBranches calls ListMergedBranchesFunc.
func (mock *RunnerMock) ListMergedBranches(ctx context.Context, repoDir string, baseBranch string) ([]string, error) {
	if mock.ListMergedBranchesFunc == nil {
		panic("RunnerMock.ListMergedBranchesFunc: method is nil but Runner.ListMergedBranches was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		RepoDir    string
		BaseBranch string
	}{
		Ctx:        ctx,
		RepoDir:    repoDir,
		BaseBranch: baseBranch,
	}
	mock.lockListMergedBranches.Lock()
	mock.calls.ListMergedBranches = append(mock.calls.ListMergedBranches, callInfo)
	mock.lockListMergedBranches.Unlock()
	return mock.ListMergedBranchesFunc(ctx, repoDir, baseBranch)
}

// ListMergedBranchesCalls gets all the calls that were made to ListMergedBranches.
// Check the length with:
//
//	len(mockedRunner.ListMergedBranchesCalls())
func (mock *RunnerMock) ListMergedBranchesCalls() []struct {
	Ctx        context.Context
	RepoDir    string
	BaseBranch string
} {
	var calls []struct {
		Ctx        context.Context
		RepoDir    string
		BaseBranch string
	}
	mock.lockListMergedBranches.RLock()
	calls = mock.calls.ListMergedBranches
	mock.lockListMergedBranches.RUnlock()
	return calls
}

// Status calls StatusFunc.
func (mock *RunnerMock) Status(ctx context.Context, repoDir string) (string, error) {
	if mock.StatusFunc == nil {
		panic("RunnerMock.StatusFunc: method is nil but Runner.Status was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		RepoDir string
	}{
		Ctx:     ctx,
		RepoDir: repoDir,
	}
	mock.lockStatus.Lock()
	mock.calls.Status = append(mock.calls.Status, callInfo)
	mock.lockStatus.Unlock()
	return mock.StatusFunc(ctx, repoDir)
}

// StatusCalls gets all the calls that were made to Status.
// Check the length with:
//
//	len(mockedRunner.StatusCalls())
func (mock *RunnerMock) StatusCalls() []struct {
	Ctx     context.Context
	RepoDir string
} {
	var calls []struct {
		Ctx     context.Context
		RepoDir string
	}
	mock.lockStatus.RLock()
	calls = mock.calls.Status
	mock.lockStatus.RUnlock()
	return calls
}
