// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/s22625/orch/internal/github"
	"sync"
)

// Ensure, that ClientMock does implement github.Client.
// If this is not the case, regenerate this file with moq.
var _ github.Client = &ClientMock{}

// ClientMock is a mock implementation of github.Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked github.Client
//		mockedClient := &ClientMock{
//			IsAvailableFunc: func() bool {
//				panic("mock out the IsAvailable method")
//			},
//			LookupPRByHeadFunc: func(repoRoot string, branch string) (*github.PR, error) {
//				panic("mock out the LookupPRByHead method")
//			},
//			LookupPRByURLFunc: func(prURL string) (*github.PR, error) {
//				panic("mock out the LookupPRByURL method")
//			},
//			RunFunc: func(args ...string) ([]byte, error) {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedClient in code that requires github.Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// IsAvailableFunc mocks the IsAvailable method.
	IsAvailableFunc func() bool

	// LookupPRByHeadFunc mocks the LookupPRByHead method.
	LookupPRByHeadFunc func(repoRoot string, branch string) (*github.PR, error)

	// LookupPRByURLFunc mocks the LookupPRByURL method.
	LookupPRByURLFunc func(prURL string) (*github.PR, error)

	// RunFunc mocks the Run method.
	RunFunc func(args ...string) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// IsAvailable holds details about calls to the IsAvailable method.
		IsAvailable []struct {
		}
		// LookupPRByHead holds details about calls to the LookupPRByHead method.
		LookupPRByHead []struct {
			// RepoRoot is the repoRoot argument value.
			RepoRoot string
			// Branch is the branch argument value.
			Branch string
		}
		// LookupPRByURL holds details about calls to the LookupPRByURL method.
		LookupPRByURL []struct {
			// PrURL is the prURL argument value.
			PrURL string
		}
		// Run holds details about calls to the Run method.
		Run []struct {
			// Args is the args argument value.
			Args []string
		}
	}
	lockIsAvailable    sync.RWMutex
	lockLookupPRByHead sync.RWMutex
	lockLookupPRByURL  sync.RWMutex
	lockRun            sync.RWMutex
}

// IsAvailable calls IsAvailableFunc.
func (mock *ClientMock) IsAvailable() bool {
	if mock.IsAvailableFunc == nil {
		panic("ClientMock.IsAvailableFunc: method is nil but Client.IsAvailable was just called")
	}
	callInfo := struct {
	}{}
	mock.lockIsAvailable.Lock()
	mock.calls.IsAvailable = append(mock.calls.IsAvailable, callInfo)
	mock.lockIsAvailable.Unlock()
	return mock.IsAvailableFunc()
}

// IsAvailableCalls gets all the calls that were made to IsAvailable.
// Check the length with:
//
//	len(mockedClient.IsAvailableCalls())
func (mock *ClientMock) IsAvailableCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIsAvailable.RLock()
	calls = mock.calls.IsAvailable
	mock.lockIsAvailable.RUnlock()
	return calls
}

// LookupPRByHead calls LookupPRByHeadFunc.
func (mock *ClientMock) LookupPRByHead(repoRoot string, branch string) (*github.PR, error) {
	if mock.LookupPRByHeadFunc == nil {
		panic("ClientMock.LookupPRByHeadFunc: method is nil but Client.LookupPRByHead was just called")
	}
	callInfo := struct {
		RepoRoot string
		Branch   string
	}{
		RepoRoot: repoRoot,
		Branch:   branch,
	}
	mock.lockLookupPRByHead.Lock()
	mock.calls.LookupPRByHead = append(mock.calls.LookupPRByHead, callInfo)
	mock.lockLookupPRByHead.Unlock()
	return mock.LookupPRByHeadFunc(repoRoot, branch)
}

// LookupPRByHeadCalls gets all the calls that were made to LookupPRByHead.
// Check the length with:
//
//	len(mockedClient.LookupPRByHeadCalls())
func (mock *ClientMock) LookupPRByHeadCalls() []struct {
	RepoRoot string
	Branch   string
} {
	var calls []struct {
		RepoRoot string
		Branch   string
	}
	mock.lockLookupPRByHead.RLock()
	calls = mock.calls.LookupPRByHead
	mock.lockLookupPRByHead.RUnlock()
	return calls
}

// LookupPRByURL calls LookupPRByURLFunc.
func (mock *ClientMock) LookupPRByURL(prURL string) (*github.PR, error) {
	if mock.LookupPRByURLFunc == nil {
		panic("ClientMock.LookupPRByURLFunc: method is nil but Client.LookupPRByURL was just called")
	}
	callInfo := struct {
		PrURL string
	}{
		PrURL: prURL,
	}
	mock.lockLookupPRByURL.Lock()
	mock.calls.LookupPRByURL = append(mock.calls.LookupPRByURL, callInfo)
	mock.lockLookupPRByURL.Unlock()
	return mock.LookupPRByURLFunc(prURL)
}

// LookupPRByURLCalls gets all the calls that were made to LookupPRByURL.
// Check the length with:
//
//	len(mockedClient.LookupPRByURLCalls())
func (mock *ClientMock) LookupPRByURLCalls() []struct {
	PrURL string
} {
	var calls []struct {
		PrURL string
	}
	mock.lockLookupPRByURL.RLock()
	calls = mock.calls.LookupPRByURL
	mock.lockLookupPRByURL.RUnlock()
	return calls
}

// Run calls RunFunc.
func (mock *ClientMock) Run(args ...string) ([]byte, error) {
	if mock.RunFunc == nil {
		panic("ClientMock.RunFunc: method is nil but Client.Run was just called")
	}
	callInfo := struct {
		Args []string
	}{
		Args: args,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(args...)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedClient.RunCalls())
func (mock *ClientMock) RunCalls() []struct {
	Args []string
} {
	var calls []struct {
		Args []string
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}
