// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/s22625/orch/internal/model"
	"github.com/s22625/orch/internal/store"
	"sync"
)

// Ensure, that StoreMock does implement store.Store.
// If this is not the case, regenerate this file with moq.
var _ store.Store = &StoreMock{}

// StoreMock is a mock implementation of store.Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked store.Store
//		mockedStore := &StoreMock{
//			AppendEventFunc: func(ref *model.RunRef, event *model.Event) error {
//				panic("mock out the AppendEvent method")
//			},
//			CreateIssueFunc: func(issue *model.Issue) error {
//				panic("mock out the CreateIssue method")
//			},
//			CreateRunFunc: func(issueID string, runID string, metadata map[string]string) (*model.Run, error) {
//				panic("mock out the CreateRun method")
//			},
//			DeleteRunFunc: func(ref *model.RunRef) error {
//				panic("mock out the DeleteRun method")
//			},
//			GetLatestRunFunc: func(issueID string) (*model.Run, error) {
//				panic("mock out the GetLatestRun method")
//			},
//			GetRunFunc: func(ref *model.RunRef) (*model.Run, error) {
//				panic("mock out the GetRun method")
//			},
//			GetRunByShortIDFunc: func(shortID string) (*model.Run, error) {
//				panic("mock out the GetRunByShortID method")
//			},
//			ListIssuesFunc: func() ([]*model.Issue, error) {
//				panic("mock out the ListIssues method")
//			},
//			ListRunsFunc: func(filter *store.ListRunsFilter) ([]*model.Run, error) {
//				panic("mock out the ListRuns method")
//			},
//			ReadAgentPromptFunc: func(ref *model.RunRef) (string, error) {
//				panic("mock out the ReadAgentPrompt method")
//			},
//			ResolveIssueFunc: func(issueID string) (*model.Issue, error) {
//				panic("mock out the ResolveIssue method")
//			},
//			RootPathFunc: func() string {
//				panic("mock out the RootPath method")
//			},
//			SetIssueStatusFunc: func(issueID string, status model.IssueStatus) error {
//				panic("mock out the SetIssueStatus method")
//			},
//			UpdateIssueFunc: func(issue *model.Issue) error {
//				panic("mock out the UpdateIssue method")
//			},
//			ValidateIssueFilesFunc: func(issueID string) (*store.ValidationResult, error) {
//				panic("mock out the ValidateIssueFiles method")
//			},
//			WriteAgentPromptFunc: func(ref *model.RunRef, content string) error {
//				panic("mock out the WriteAgentPrompt method")
//			},
//		}
//
//		// use mockedStore in code that requires store.Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// AppendEventFunc mocks the AppendEvent method.
	AppendEventFunc func(ref *model.RunRef, event *model.Event) error

	// CreateIssueFunc mocks the CreateIssue method.
	CreateIssueFunc func(issue *model.Issue) error

	// CreateRunFunc mocks the CreateRun method.
	CreateRunFunc func(issueID string, runID string, metadata map[string]string) (*model.Run, error)

	// DeleteRunFunc mocks the DeleteRun method.
	DeleteRunFunc func(ref *model.RunRef) error

	// GetLatestRunFunc mocks the GetLatestRun method.
	GetLatestRunFunc func(issueID string) (*model.Run, error)

	// GetRunFunc mocks the GetRun method.
	GetRunFunc func(ref *model.RunRef) (*model.Run, error)

	// GetRunByShortIDFunc mocks the GetRunByShortID method.
	GetRunByShortIDFunc func(shortID string) (*model.Run, error)

	// ListIssuesFunc mocks the ListIssues method.
	ListIssuesFunc func() ([]*model.Issue, error)

	// ListRunsFunc mocks the ListRuns method.
	ListRunsFunc func(filter *store.ListRunsFilter) ([]*model.Run, error)

	// ReadAgentPromptFunc mocks the ReadAgentPrompt method.
	ReadAgentPromptFunc func(ref *model.RunRef) (string, error)

	// ResolveIssueFunc mocks the ResolveIssue method.
	ResolveIssueFunc func(issueID string) (*model.Issue, error)

	// RootPathFunc mocks the RootPath method.
	RootPathFunc func() string

	// SetIssueStatusFunc mocks the SetIssueStatus method.
	SetIssueStatusFunc func(issueID string, status model.IssueStatus) error

	// UpdateIssueFunc mocks the UpdateIssue method.
	UpdateIssueFunc func(issue *model.Issue) error

	// ValidateIssueFilesFunc mocks the ValidateIssueFiles method.
	ValidateIssueFilesFunc func(issueID string) (*store.ValidationResult, error)

	// WriteAgentPromptFunc mocks the WriteAgentPrompt method.
	WriteAgentPromptFunc func(ref *model.RunRef, content string) error

	// calls tracks calls to the methods.
	calls struct {
		// AppendEvent holds details about calls to the AppendEvent method.
		AppendEvent []struct {
			// Ref is the ref argument value.
			Ref *model.RunRef
			// Event is the event argument value.
			Event *model.Event
		}
		// CreateIssue holds details about calls to the CreateIssue method.
		CreateIssue []struct {
			// Issue is the issue argument value.
			Issue *model.Issue
		}
		// CreateRun holds details about calls to the CreateRun method.
		CreateRun []struct {
			// IssueID is the issueID argument value.
			IssueID string
			// RunID is the runID argument value.
			RunID string
			// Metadata is the metadata argument value.
			Metadata map[string]string
		}
		// DeleteRun holds details about calls to the DeleteRun method.
		DeleteRun []struct {
			// Ref is the ref argument value.
			Ref *model.RunRef
		}
		// GetLatestRun holds details about calls to the GetLatestRun method.
		GetLatestRun []struct {
			// IssueID is the issueID argument value.
			IssueID string
		}
		// GetRun holds details about calls to the GetRun method.
		GetRun []struct {
			// Ref is the ref argument value.
			Ref *model.RunRef
		}
		// GetRunByShortID holds details about calls to the GetRunByShortID method.
		GetRunByShortID []struct {
			// ShortID is the shortID argument value.
			ShortID string
		}
		// ListIssues holds details about calls to the ListIssues method.
		ListIssues []struct {
		}
		// ListRuns holds details about calls to the ListRuns method.
		ListRuns []struct {
			// Filter is the filter argument value.
			Filter *store.ListRunsFilter
		}
		// ReadAgentPrompt holds details about calls to the ReadAgentPrompt method.
		ReadAgentPrompt []struct {
			// Ref is the ref argument value.
			Ref *model.RunRef
		}
		// ResolveIssue holds details about calls to the ResolveIssue method.
		ResolveIssue []struct {
			// IssueID is the issueID argument value.
			IssueID string
		}
		// RootPath holds details about calls to the RootPath method.
		RootPath []struct {
		}
		// SetIssueStatus holds details about calls to the SetIssueStatus method.
		SetIssueStatus []struct {
			// IssueID is the issueID argument value.
			IssueID string
			// Status is the status argument value.
			Status model.IssueStatus
		}
		// UpdateIssue holds details about calls to the UpdateIssue method.
		UpdateIssue []struct {
			// Issue is the issue argument value.
			Issue *model.Issue
		}
		// ValidateIssueFiles holds details about calls to the ValidateIssueFiles method.
		ValidateIssueFiles []struct {
			// IssueID is the issueID argument value.
			IssueID string
		}
		// WriteAgentPrompt holds details about calls to the WriteAgentPrompt method.
		WriteAgentPrompt []struct {
			// Ref is the ref argument value.
			Ref *model.RunRef
			// Content is the content argument value.
			Content string
		}
	}
	lockAppendEvent        sync.RWMutex
	lockCreateIssue        sync.RWMutex
	lockCreateRun          sync.RWMutex
	lockDeleteRun          sync.RWMutex
	lockGetLatestRun       sync.RWMutex
	lockGetRun             sync.RWMutex
	lockGetRunByShortID    sync.RWMutex
	lockListIssues         sync.RWMutex
	lockListRuns           sync.RWMutex
	lockReadAgentPrompt    sync.RWMutex
	lockResolveIssue       sync.RWMutex
	lockRootPath           sync.RWMutex
	lockSetIssueStatus     sync.RWMutex
	lockUpdateIssue        sync.RWMutex
	lockValidateIssueFiles sync.RWMutex
	lockWriteAgentPrompt   sync.RWMutex
}

// AppendEvent calls AppendEventFunc.
func (mock *StoreMock) AppendEvent(ref *model.RunRef, event *model.Event) error {
	if mock.AppendEventFunc == nil {
		panic("StoreMock.AppendEventFunc: method is nil but Store.AppendEvent was just called")
	}
	callInfo := struct {
		Ref   *model.RunRef
		Event *model.Event
	}{
		Ref:   ref,
		Event: event,
	}
	mock.lockAppendEvent.Lock()
	mock.calls.AppendEvent = append(mock.calls.AppendEvent, callInfo)
	mock.lockAppendEvent.Unlock()
	return mock.AppendEventFunc(ref, event)
}

// AppendEventCalls gets all the calls that were made to AppendEvent.
// Check the length with:
//
//	len(mockedStore.AppendEventCalls())
func (mock *StoreMock) AppendEventCalls() []struct {
	Ref   *model.RunRef
	Event *model.Event
} {
	var calls []struct {
		Ref   *model.RunRef
		Event *model.Event
	}
	mock.lockAppendEvent.RLock()
	calls = mock.calls.AppendEvent
	mock.lockAppendEvent.RUnlock()
	return calls
}

// CreateIssue calls CreateIssueFunc.
func (mock *StoreMock) CreateIssue(issue *model.Issue) error {
	if mock.CreateIssueFunc == nil {
		panic("StoreMock.CreateIssueFunc: method is nil but Store.CreateIssue was just called")
	}
	callInfo := struct {
		Issue *model.Issue
	}{
		Issue: issue,
	}
	mock.lockCreateIssue.Lock()
	mock.calls.CreateIssue = append(mock.calls.CreateIssue, callInfo)
	mock.lockCreateIssue.Unlock()
	return mock.CreateIssueFunc(issue)
}

// CreateIssueCalls gets all the calls that were made to CreateIssue.
// Check the length with:
//
//	len(mockedStore.CreateIssueCalls())
func (mock *StoreMock) CreateIssueCalls() []struct {
	Issue *model.Issue
} {
	var calls []struct {
		Issue *model.Issue
	}
	mock.lockCreateIssue.RLock()
	calls = mock.calls.CreateIssue
	mock.lockCreateIssue.RUnlock()
	return calls
}

// CreateRun calls CreateRunFunc.
func (mock *StoreMock) CreateRun(issueID string, runID string, metadata map[string]string) (*model.Run, error) {
	if mock.CreateRunFunc == nil {
		panic("StoreMock.CreateRunFunc: method is nil but Store.CreateRun was just called")
	}
	callInfo := struct {
		IssueID  string
		RunID    string
		Metadata map[string]string
	}{
		IssueID:  issueID,
		RunID:    runID,
		Metadata: metadata,
	}
	mock.lockCreateRun.Lock()
	mock.calls.CreateRun = append(mock.calls.CreateRun, callInfo)
	mock.lockCreateRun.Unlock()
	return mock.CreateRunFunc(issueID, runID, metadata)
}

// CreateRunCalls gets all the calls that were made to CreateRun.
// Check the length with:
//
//	len(mockedStore.CreateRunCalls())
func (mock *StoreMock) CreateRunCalls() []struct {
	IssueID  string
	RunID    string
	Metadata map[string]string
} {
	var calls []struct {
		IssueID  string
		RunID    string
		Metadata map[string]string
	}
	mock.lockCreateRun.RLock()
	calls = mock.calls.CreateRun
	mock.lockCreateRun.RUnlock()
	return calls
}

// DeleteRun calls DeleteRunFunc.
func (mock *StoreMock) DeleteRun(ref *model.RunRef) error {
	if mock.DeleteRunFunc == nil {
		panic("StoreMock.DeleteRunFunc: method is nil but Store.DeleteRun was just called")
	}
	callInfo := struct {
		Ref *model.RunRef
	}{
		Ref: ref,
	}
	mock.lockDeleteRun.Lock()
	mock.calls.DeleteRun = append(mock.calls.DeleteRun, callInfo)
	mock.lockDeleteRun.Unlock()
	return mock.DeleteRunFunc(ref)
}

// DeleteRunCalls gets all the calls that were made to DeleteRun.
// Check the length with:
//
//	len(mockedStore.DeleteRunCalls())
func (mock *StoreMock) DeleteRunCalls() []struct {
	Ref *model.RunRef
} {
	var calls []struct {
		Ref *model.RunRef
	}
	mock.lockDeleteRun.RLock()
	calls = mock.calls.DeleteRun
	mock.lockDeleteRun.RUnlock()
	return calls
}

// GetLatestRun calls GetLatestRunFunc.
func (mock *StoreMock) GetLatestRun(issueID string) (*model.Run, error) {
	if mock.GetLatestRunFunc == nil {
		panic("StoreMock.GetLatestRunFunc: method is nil but Store.GetLatestRun was just called")
	}
	callInfo := struct {
		IssueID string
	}{
		IssueID: issueID,
	}
	mock.lockGetLatestRun.Lock()
	mock.calls.GetLatestRun = append(mock.calls.GetLatestRun, callInfo)
	mock.lockGetLatestRun.Unlock()
	return mock.GetLatestRunFunc(issueID)
}

// GetLatestRunCalls gets all the calls that were made to GetLatestRun.
// Check the length with:
//
//	len(mockedStore.GetLatestRunCalls())
func (mock *StoreMock) GetLatestRunCalls() []struct {
	IssueID string
} {
	var calls []struct {
		IssueID string
	}
	mock.lockGetLatestRun.RLock()
	calls = mock.calls.GetLatestRun
	mock.lockGetLatestRun.RUnlock()
	return calls
}

// GetRun calls GetRunFunc.
func (mock *StoreMock) GetRun(ref *model.RunRef) (*model.Run, error) {
	if mock.GetRunFunc == nil {
		panic("StoreMock.GetRunFunc: method is nil but Store.GetRun was just called")
	}
	callInfo := struct {
		Ref *model.RunRef
	}{
		Ref: ref,
	}
	mock.lockGetRun.Lock()
	mock.calls.GetRun = append(mock.calls.GetRun, callInfo)
	mock.lockGetRun.Unlock()
	return mock.GetRunFunc(ref)
}

// GetRunCalls gets all the calls that were made to GetRun.
// Check the length with:
//
//	len(mockedStore.GetRunCalls())
func (mock *StoreMock) GetRunCalls() []struct {
	Ref *model.RunRef
} {
	var calls []struct {
		Ref *model.RunRef
	}
	mock.lockGetRun.RLock()
	calls = mock.calls.GetRun
	mock.lockGetRun.RUnlock()
	return calls
}

// GetRunByShortID calls GetRunByShortIDFunc.
func (mock *StoreMock) GetRunByShortID(shortID string) (*model.Run, error) {
	if mock.GetRunByShortIDFunc == nil {
		panic("StoreMock.GetRunByShortIDFunc: method is nil but Store.GetRunByShortID was just called")
	}
	callInfo := struct {
		ShortID string
	}{
		ShortID: shortID,
	}
	mock.lockGetRunByShortID.Lock()
	mock.calls.GetRunByShortID = append(mock.calls.GetRunByShortID, callInfo)
	mock.lockGetRunByShortID.Unlock()
	return mock.GetRunByShortIDFunc(shortID)
}

// GetRunByShortIDCalls gets all the calls that were made to GetRunByShortID.
// Check the length with:
//
//	len(mockedStore.GetRunByShortIDCalls())
func (mock *StoreMock) GetRunByShortIDCalls() []struct {
	ShortID string
} {
	var calls []struct {
		ShortID string
	}
	mock.lockGetRunByShortID.RLock()
	calls = mock.calls.GetRunByShortID
	mock.lockGetRunByShortID.RUnlock()
	return calls
}

// ListIssues calls ListIssuesFunc.
func (mock *StoreMock) ListIssues() ([]*model.Issue, error) {
	if mock.ListIssuesFunc == nil {
		panic("StoreMock.ListIssuesFunc: method is nil but Store.ListIssues was just called")
	}
	callInfo := struct {
	}{}
	mock.lockListIssues.Lock()
	mock.calls.ListIssues = append(mock.calls.ListIssues, callInfo)
	mock.lockListIssues.Unlock()
	return mock.ListIssuesFunc()
}

// ListIssuesCalls gets all the calls that were made to ListIssues.
// Check the length with:
//
//	len(mockedStore.ListIssuesCalls())
func (mock *StoreMock) ListIssuesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockListIssues.RLock()
	calls = mock.calls.ListIssues
	mock.lockListIssues.RUnlock()
	return calls
}

// ListRuns calls ListRunsFunc.
func (mock *StoreMock) ListRuns(filter *store.ListRunsFilter) ([]*model.Run, error) {
	if mock.ListRunsFunc == nil {
		panic("StoreMock.ListRunsFunc: method is nil but Store.ListRuns was just called")
	}
	callInfo := struct {
		Filter *store.ListRunsFilter
	}{
		Filter: filter,
	}
	mock.lockListRuns.Lock()
	mock.calls.ListRuns = append(mock.calls.ListRuns, callInfo)
	mock.lockListRuns.Unlock()
	return mock.ListRunsFunc(filter)
}

// ListRunsCalls gets all the calls that were made to ListRuns.
// Check the length with:
//
//	len(mockedStore.ListRunsCalls())
func (mock *StoreMock) ListRunsCalls() []struct {
	Filter *store.ListRunsFilter
} {
	var calls []struct {
		Filter *store.ListRunsFilter
	}
	mock.lockListRuns.RLock()
	calls = mock.calls.ListRuns
	mock.lockListRuns.RUnlock()
	return calls
}

// ReadAgentPrompt calls ReadAgentPromptFunc.
func (mock *StoreMock) ReadAgentPrompt(ref *model.RunRef) (string, error) {
	if mock.ReadAgentPromptFunc == nil {
		panic("StoreMock.ReadAgentPromptFunc: method is nil but Store.ReadAgentPrompt was just called")
	}
	callInfo := struct {
		Ref *model.RunRef
	}{
		Ref: ref,
	}
	mock.lockReadAgentPrompt.Lock()
	mock.calls.ReadAgentPrompt = append(mock.calls.ReadAgentPrompt, callInfo)
	mock.lockReadAgentPrompt.Unlock()
	return mock.ReadAgentPromptFunc(ref)
}

// ReadAgentPromptCalls gets all the calls that were made to ReadAgentPrompt.
// Check the length with:
//
//	len(mockedStore.ReadAgentPromptCalls())
func (mock *StoreMock) ReadAgentPromptCalls() []struct {
	Ref *model.RunRef
} {
	var calls []struct {
		Ref *model.RunRef
	}
	mock.lockReadAgentPrompt.RLock()
	calls = mock.calls.ReadAgentPrompt
	mock.lockReadAgentPrompt.RUnlock()
	return calls
}

// ResolveIssue calls ResolveIssueFunc.
func (mock *StoreMock) ResolveIssue(issueID string) (*model.Issue, error) {
	if mock.ResolveIssueFunc == nil {
		panic("StoreMock.ResolveIssueFunc: method is nil but Store.ResolveIssue was just called")
	}
	callInfo := struct {
		IssueID string
	}{
		IssueID: issueID,
	}
	mock.lockResolveIssue.Lock()
	mock.calls.ResolveIssue = append(mock.calls.ResolveIssue, callInfo)
	mock.lockResolveIssue.Unlock()
	return mock.ResolveIssueFunc(issueID)
}

// ResolveIssueCalls gets all the calls that were made to ResolveIssue.
// Check the length with:
//
//	len(mockedStore.ResolveIssueCalls())
func (mock *StoreMock) ResolveIssueCalls() []struct {
	IssueID string
} {
	var calls []struct {
		IssueID string
	}
	mock.lockResolveIssue.RLock()
	calls = mock.calls.ResolveIssue
	mock.lockResolveIssue.RUnlock()
	return calls
}

// RootPath calls RootPathFunc.
func (mock *StoreMock) RootPath() string {
	if mock.RootPathFunc == nil {
		panic("StoreMock.RootPathFunc: method is nil but Store.RootPath was just called")
	}
	callInfo := struct {
	}{}
	mock.lockRootPath.Lock()
	mock.calls.RootPath = append(mock.calls.RootPath, callInfo)
	mock.lockRootPath.Unlock()
	return mock.RootPathFunc()
}

// RootPathCalls gets all the calls that were made to RootPath.
// Check the length with:
//
//	len(mockedStore.RootPathCalls())
func (mock *StoreMock) RootPathCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockRootPath.RLock()
	calls = mock.calls.RootPath
	mock.lockRootPath.RUnlock()
	return calls
}

// SetIssueStatus calls SetIssueStatusFunc.
func (mock *StoreMock) SetIssueStatus(issueID string, status model.IssueStatus) error {
	if mock.SetIssueStatusFunc == nil {
		panic("StoreMock.SetIssueStatusFunc: method is nil but Store.SetIssueStatus was just called")
	}
	callInfo := struct {
		IssueID string
		Status  model.IssueStatus
	}{
		IssueID: issueID,
		Status:  status,
	}
	mock.lockSetIssueStatus.Lock()
	mock.calls.SetIssueStatus = append(mock.calls.SetIssueStatus, callInfo)
	mock.lockSetIssueStatus.Unlock()
	return mock.SetIssueStatusFunc(issueID, status)
}

// SetIssueStatusCalls gets all the calls that were made to SetIssueStatus.
// Check the length with:
//
//	len(mockedStore.SetIssueStatusCalls())
func (mock *StoreMock) SetIssueStatusCalls() []struct {
	IssueID string
	Status  model.IssueStatus
} {
	var calls []struct {
		IssueID string
		Status  model.IssueStatus
	}
	mock.lockSetIssueStatus.RLock()
	calls = mock.calls.SetIssueStatus
	mock.lockSetIssueStatus.RUnlock()
	return calls
}

// UpdateIssue calls UpdateIssueFunc.
func (mock *StoreMock) UpdateIssue(issue *model.Issue) error {
	if mock.UpdateIssueFunc == nil {
		panic("StoreMock.UpdateIssueFunc: method is nil but Store.UpdateIssue was just called")
	}
	callInfo := struct {
		Issue *model.Issue
	}{
		Issue: issue,
	}
	mock.lockUpdateIssue.Lock()
	mock.calls.UpdateIssue = append(mock.calls.UpdateIssue, callInfo)
	mock.lockUpdateIssue.Unlock()
	return mock.UpdateIssueFunc(issue)
}

// UpdateIssueCalls gets all the calls that were made to UpdateIssue.
// Check the length with:
//
//	len(mockedStore.UpdateIssueCalls())
func (mock *StoreMock) UpdateIssueCalls() []struct {
	Issue *model.Issue
} {
	var calls []struct {
		Issue *model.Issue
	}
	mock.lockUpdateIssue.RLock()
	calls = mock.calls.UpdateIssue
	mock.lockUpdateIssue.RUnlock()
	return calls
}

// ValidateIssueFiles calls ValidateIssueFilesFunc.
func (mock *StoreMock) ValidateIssueFiles(issueID string) (*store.ValidationResult, error) {
	if mock.ValidateIssueFilesFunc == nil {
		panic("StoreMock.ValidateIssueFilesFunc: method is nil but Store.ValidateIssueFiles was just called")
	}
	callInfo := struct {
		IssueID string
	}{
		IssueID: issueID,
	}
	mock.lockValidateIssueFiles.Lock()
	mock.calls.ValidateIssueFiles = append(mock.calls.ValidateIssueFiles, callInfo)
	mock.lockValidateIssueFiles.Unlock()
	return mock.ValidateIssueFilesFunc(issueID)
}

// ValidateIssueFilesCalls gets all the calls that were made to ValidateIssueFiles.
// Check the length with:
//
//	len(mockedStore.ValidateIssueFilesCalls())
func (mock *StoreMock) ValidateIssueFilesCalls() []struct {
	IssueID string
} {
	var calls []struct {
		IssueID string
	}
	mock.lockValidateIssueFiles.RLock()
	calls = mock.calls.ValidateIssueFiles
	mock.lockValidateIssueFiles.RUnlock()
	return calls
}

// WriteAgentPrompt calls WriteAgentPromptFunc.
func (mock *StoreMock) WriteAgentPrompt(ref *model.RunRef, content string) error {
	if mock.WriteAgentPromptFunc == nil {
		panic("StoreMock.WriteAgentPromptFunc: method is nil but Store.WriteAgentPrompt was just called")
	}
	callInfo := struct {
		Ref     *model.RunRef
		Content string
	}{
		Ref:     ref,
		Content: content,
	}
	mock.lockWriteAgentPrompt.Lock()
	mock.calls.WriteAgentPrompt = append(mock.calls.WriteAgentPrompt, callInfo)
	mock.lockWriteAgentPrompt.Unlock()
	return mock.WriteAgentPromptFunc(ref, content)
}

// WriteAgentPromptCalls gets all the calls that were made to WriteAgentPrompt.
// Check the length with:
//
//	len(mockedStore.WriteAgentPromptCalls())
func (mock *StoreMock) WriteAgentPromptCalls() []struct {
	Ref     *model.RunRef
	Content string
} {
	var calls []struct {
		Ref     *model.RunRef
		Content string
	}
	mock.lockWriteAgentPrompt.RLock()
	calls = mock.calls.WriteAgentPrompt
	mock.lockWriteAgentPrompt.RUnlock()
	return calls
}
